"x"
"to" : 4116
"the" : 4105
"of" : 3572
"and" : 3491
"her" : 2551
"a" : 2092
"i" : 2004
"in" : 1979
"was" : 1861
"it" : 1757
"she" : 1613
"that" : 1385
"be" : 1305
"for" : 1262
"not" : 1248
"as" : 1221
"you" : 1191
"he" : 1108
"his" : 1021
"had" : 998
"with" : 992
"but" : 886
"at" : 839
"have" : 819
"is" : 760
"by" : 750
"s" : 701
"on" : 696
"elinor" : 685
"all" : 656
"so" : 644
"him" : 642
"my" : 628
"which" : 593
"could" : 578
"no" : 568
"marianne" : 566
"from" : 541
"mrs" : 530
"they" : 521
"would" : 515
"very" : 500
"their" : 498
"them" : 468
"me" : 444
"what" : 444
"been" : 441
"were" : 441
"this" : 436
"more" : 407
"said" : 397
"any" : 390
"your" : 386
"every" : 377
"will" : 363
"than" : 360
"such" : 359
"or" : 356
"an" : 351
"one" : 331
"do" : 327
"when" : 306
"if" : 293
"much" : 290
"only" : 287
"must" : 283
"sister" : 282
"am" : 273
"own" : 272
"who" : 269
"edward" : 263
"mother" : 258
"herself" : 255
"dashwood" : 252
"did" : 247
"there" : 242
"well" : 240
"time" : 239
"now" : 238
"how" : 236
"should" : 236
"are" : 234
"know" : 232
"jennings" : 230
"can" : 218
"though" : 216
"we" : 216
"willoughby" : 216
"might" : 215
"some" : 215
"has" : 213
"miss" : 210
"think" : 210
"after" : 203
"before" : 201
"never" : 189
"nothing" : 189
"other" : 188
"too" : 188
"lucy" : 186
"thing" : 185
"soon" : 181
"mr" : 178
"good" : 177
"colonel" : 176
"may" : 175
"without" : 174
"see" : 173
"ever" : 169
"being" : 165
"john" : 164
"house" : 161
"out" : 161
"first" : 160
"little" : 160
"say" : 160
"however" : 155
"most" : 154
"then" : 154
"two" : 153
"day" : 150
"great" : 149
"again" : 147
"about" : 144
"brandon" : 144
"lady" : 142
"make" : 140
"made" : 138
"sure" : 136
"its" : 133
"ferrars" : 130
"shall" : 128
"heart" : 127
"give" : 126
"even" : 125
"always" : 124
"man" : 121
"sir" : 120
"room" : 119
"dear" : 118
"thought" : 116
"into" : 115
"himself" : 114
"saw" : 114
"away" : 112
"up" : 111
"while" : 109
"felt" : 106
"long" : 104
"enough" : 103
"last" : 103
"myself" : 103
"young" : 103
"come" : 102
"middleton" : 102
"replied" : 102
"same" : 102
"happy" : 100
"indeed" : 100
"many" : 100
"mind" : 100
"over" : 100
"still" : 100
"moment" : 99
"go" : 98
"left" : 98
"upon" : 98
"less" : 97
"kind" : 95
"both" : 93
"quite" : 93
"therefore" : 93
"world" : 93
"believe" : 91
"seemed" : 91
"where" : 91
"tell" : 90
"us" : 90
"barton" : 89
"came" : 89
"cannot" : 89
"hope" : 88
"nor" : 88
"cried" : 87
"morning" : 87
"perhaps" : 87
"place" : 87
"really" : 86
"town" : 86
"almost" : 85
"present" : 84
"brother" : 83
"family" : 83
"like" : 83
"till" : 83
"affection" : 79
"another" : 79
"few" : 79
"better" : 78
"heard" : 78
"yet" : 78
"down" : 77
"love" : 77
"palmer" : 77
"letter" : 76
"something" : 75
"once" : 74
"our" : 74
"rather" : 74
"way" : 74
"feelings" : 73
"together" : 73
"wish" : 73
"immediately" : 72
"done" : 71
"found" : 71
"gave" : 71
"poor" : 71
"hear" : 70
"least" : 70
"oh" : 70
"person" : 70
"home" : 69
"spirits" : 69
"told" : 69
"whom" : 69
"between" : 68
"far" : 68
"just" : 68
"look" : 68
"subject" : 68
"woman" : 68
"pleasure" : 67
"because" : 66
"feel" : 66
"happiness" : 66
"whole" : 66
"against" : 65
"hardly" : 65
"towards" : 65
"acquaintance" : 64
"behaviour" : 64
"these" : 64
"comfort" : 63
"engagement" : 63
"opinion" : 63
"friends" : 62
"knew" : 62
"three" : 62
"visit" : 62
"certainly" : 61
"cottage" : 61
"here" : 61
"looked" : 61
"since" : 61
"speak" : 61
"yes" : 61
"known" : 60
"others" : 60
"t" : 60
"going" : 59
"life" : 59
"within" : 59
"attention" : 58
"brought" : 58
"each" : 58
"having" : 58
"leave" : 58
"off" : 57
"short" : 57
"continued" : 56
"does" : 56
"eyes" : 56
"half" : 56
"manner" : 56
"seen" : 56
"side" : 56
"end" : 55
"find" : 55
"friend" : 55
"general" : 55
"suppose" : 55
"given" : 54
"married" : 54
"people" : 54
"rest" : 54
"situation" : 54
"wished" : 54
"year" : 54
"longer" : 53
"norland" : 53
"reason" : 53
"body" : 52
"next" : 52
"often" : 52
"park" : 52
"passed" : 52
"returned" : 52
"took" : 52
"evening" : 51
"under" : 51
"voice" : 51
"chapter" : 50
"ill" : 50
"regard" : 50
"already" : 49
"farther" : 49
"possible" : 49
"street" : 49
"those" : 49
"went" : 49
"why" : 49
"wife" : 49
"years" : 49
"fanny" : 48
"part" : 48
"party" : 48
"sisters" : 48
"whose" : 48
"word" : 48
"determined" : 47
"interest" : 47
"matter" : 47
"minutes" : 47
"obliged" : 47
"thousand" : 47
"able" : 46
"beyond" : 46
"business" : 46
"daughter" : 46
"doubt" : 46
"else" : 46
"neither" : 46
"particular" : 46
"days" : 45
"power" : 45
"take" : 45
"account" : 44
"glad" : 44
"marriage" : 44
"old" : 44
"whether" : 44
"called" : 43
"entirely" : 43
"husband" : 43
"name" : 43
"perfectly" : 43
"put" : 43
"want" : 43
"began" : 42
"directly" : 42
"engaged" : 42
"hand" : 42
"kindness" : 42
"mean" : 42
"return" : 42
"added" : 41
"carriage" : 41
"child" : 41
"pounds" : 41
"seeing" : 41
"back" : 40
"conversation" : 40
"entered" : 40
"equally" : 40
"four" : 40
"surprise" : 40
"talk" : 40
"expected" : 39
"received" : 39
"saying" : 39
"whatever" : 39
"door" : 38
"fortune" : 38
"giving" : 38
"greater" : 38
"hours" : 38
"ma" : 38
"means" : 38
"point" : 38
"real" : 38
"spent" : 38
"steele" : 38
"themselves" : 38
"yourself" : 38
"coming" : 37
"conduct" : 37
"head" : 37
"months" : 37
"object" : 37
"robert" : 37
"sat" : 37
"satisfaction" : 37
"settled" : 37
"silent" : 37
"through" : 37
"wonder" : 37
"ask" : 36
"case" : 36
"common" : 36
"dare" : 36
"dashwoods" : 36
"girl" : 36
"hour" : 36
"impossible" : 36
"live" : 36
"living" : 36
"margaret" : 36
"open" : 36
"ought" : 36
"pretty" : 36
"appeared" : 35
"arrival" : 35
"call" : 35
"gone" : 35
"london" : 35
"night" : 35
"ready" : 35
"son" : 35
"spite" : 35
"spoke" : 35
"attachment" : 34
"character" : 34
"either" : 34
"manners" : 34
"particularly" : 34
"sorry" : 34
"week" : 34
"afterwards" : 33
"answer" : 33
"care" : 33
"children" : 33
"country" : 33
"deal" : 33
"five" : 33
"ladies" : 33
"law" : 33
"sake" : 33
"set" : 33
"alone" : 32
"assure" : 32
"certain" : 32
"get" : 32
"invitation" : 32
"nature" : 32
"near" : 32
"new" : 32
"pleased" : 32
"right" : 32
"sense" : 32
"silence" : 32
"talked" : 32
"confidence" : 31
"convinced" : 31
"different" : 31
"fancy" : 31
"former" : 31
"instantly" : 31
"keep" : 31
"believed" : 30
"comfortable" : 30
"course" : 30
"delaford" : 30
"father" : 30
"full" : 30
"happened" : 30
"judgment" : 30
"let" : 30
"natural" : 30
"stay" : 30
"steeles" : 30
"table" : 30
"usual" : 30
"wanted" : 30
"wishes" : 30
"anxious" : 29
"change" : 29
"circumstances" : 29
"company" : 29
"doing" : 29
"easily" : 29
"gentleman" : 29
"kept" : 29
"lord" : 29
"marry" : 29
"necessary" : 29
"opportunity" : 29
"remained" : 29
"self" : 29
"small" : 29
"sometimes" : 29
"taken" : 29
"walked" : 29
"affair" : 28
"appearance" : 28
"concern" : 28
"countenance" : 28
"drawing" : 28
"feeling" : 28
"future" : 28
"greatest" : 28
"knowledge" : 28
"likely" : 28
"misery" : 28
"question" : 28
"repeated" : 28
"resolved" : 28
"strong" : 28
"words" : 28
"bed" : 27
"cleveland" : 27
"considered" : 27
"daughters" : 27
"declared" : 27
"exactly" : 27
"expect" : 27
"favour" : 27
"got" : 27
"handsome" : 27
"hearing" : 27
"notice" : 27
"occasion" : 27
"past" : 27
"round" : 27
"suffered" : 27
"talking" : 27
"taste" : 27
"truth" : 27
"turned" : 27
"acquainted" : 26
"allow" : 26
"assured" : 26
"best" : 26
"devonshire" : 26
"distress" : 26
"exceedingly" : 26
"expectation" : 26
"fear" : 26
"large" : 26
"likewise" : 26
"low" : 26
"money" : 26
"produced" : 26
"resolution" : 26
"satisfied" : 26
"state" : 26
"surprised" : 26
"understand" : 26
"advantage" : 25
"agreeable" : 25
"anything" : 25
"event" : 25
"face" : 25
"favourite" : 25
"fine" : 25
"latter" : 25
"meeting" : 25
"otherwise" : 25
"pain" : 25
"scarcely" : 25
"use" : 25
"answered" : 24
"appear" : 24
"charlotte" : 24
"cold" : 24
"curiosity" : 24
"delight" : 24
"desire" : 24
"dinner" : 24
"don" : 24
"fixed" : 24
"forced" : 24
"idea" : 24
"joy" : 24
"late" : 24
"men" : 24
"met" : 24
"painful" : 24
"proper" : 24
"seems" : 24
"society" : 24
"supposed" : 24
"taking" : 24
"ten" : 24
"thoughts" : 24
"afraid" : 23
"bear" : 23
"disappointment" : 23
"earnest" : 23
"effect" : 23
"formed" : 23
"immediate" : 23
"income" : 23
"knowing" : 23
"making" : 23
"probably" : 23
"reached" : 23
"regret" : 23
"remember" : 23
"serious" : 23
"servant" : 23
"smile" : 23
"strange" : 23
"tears" : 23
"things" : 23
"true" : 23
"unfortunate" : 23
"weeks" : 23
"window" : 23
"worth" : 23
"admiration" : 22
"affectionate" : 22
"asked" : 22
"connection" : 22
"consider" : 22
"constant" : 22
"danger" : 22
"easy" : 22
"journey" : 22
"leaving" : 22
"meet" : 22
"merely" : 22
"plan" : 22
"prevent" : 22
"promise" : 22
"read" : 22
"respect" : 22
"share" : 22
"sitting" : 22
"tried" : 22
"wrong" : 22
"address" : 21
"among" : 21
"arrived" : 21
"avoid" : 21
"beauty" : 21
"chance" : 21
"conviction" : 21
"disposed" : 21
"disposition" : 21
"eager" : 21
"emotion" : 21
"equal" : 21
"exertion" : 21
"fond" : 21
"hundred" : 21
"looking" : 21
"meant" : 21
"melancholy" : 21
"mistaken" : 21
"sent" : 21
"speaking" : 21
"temper" : 21
"thus" : 21
"view" : 21
"wait" : 21
"above" : 20
"compassion" : 20
"delighted" : 20
"early" : 20
"eldest" : 20
"elegance" : 20
"enjoyment" : 20
"forward" : 20
"friendship" : 20
"inquiry" : 20
"letters" : 20
"lived" : 20
"loss" : 20
"lost" : 20
"particulars" : 20
"seem" : 20
"smallest" : 20
"soul" : 20
"times" : 20
"unhappy" : 20
"used" : 20
"walk" : 20
"age" : 19
"breakfast" : 19
"circumstance" : 19
"companion" : 19
"consequence" : 19
"difference" : 19
"difficulty" : 19
"discourse" : 19
"estate" : 19
"eye" : 19
"help" : 19
"hoped" : 19
"indifference" : 19
"liberty" : 19
"mentioned" : 19
"middletons" : 19
"music" : 19
"none" : 19
"pity" : 19
"quiet" : 19
"required" : 19
"secret" : 19
"stairs" : 19
"staying" : 19
"tenderness" : 19
"weather" : 19
"writing" : 19
"air" : 18
"alarm" : 18
"allenham" : 18
"anxiety" : 18
"astonishment" : 18
"attended" : 18
"become" : 18
"calm" : 18
"capable" : 18
"delightful" : 18
"entrance" : 18
"especially" : 18
"esteem" : 18
"followed" : 18
"gratitude" : 18
"hair" : 18
"honour" : 18
"hopes" : 18
"joined" : 18
"mine" : 18
"moments" : 18
"necessity" : 18
"nobody" : 18
"observation" : 18
"overcome" : 18
"praise" : 18
"recollection" : 18
"relief" : 18
"second" : 18
"sight" : 18
"smith" : 18
"style" : 18
"thinking" : 18
"unable" : 18
"understanding" : 18
"agitation" : 17
"allowed" : 17
"amiable" : 17
"attempt" : 17
"became" : 17
"behind" : 17
"berkeley" : 17
"bring" : 17
"calmness" : 17
"charming" : 17
"composure" : 17
"cousins" : 17
"difficulties" : 17
"disappointed" : 17
"ease" : 17
"except" : 17
"excuse" : 17
"hands" : 17
"inclination" : 17
"information" : 17
"intelligence" : 17
"led" : 17
"looks" : 17
"morton" : 17
"need" : 17
"parties" : 17
"pause" : 17
"pray" : 17
"simple" : 17
"spirit" : 17
"thirty" : 17
"uncle" : 17
"warmth" : 17
"welcome" : 17
"worse" : 17
"affliction" : 16
"aware" : 16
"carried" : 16
"cheerfulness" : 16
"civil" : 16
"civility" : 16
"combe" : 16
"declare" : 16
"everything" : 16
"girls" : 16
"grave" : 16
"harley" : 16
"indifferent" : 16
"influence" : 16
"informed" : 16
"laughed" : 16
"loved" : 16
"opinions" : 16
"persuaded" : 16
"purpose" : 16
"quitted" : 16
"receive" : 16
"relations" : 16
"rich" : 16
"turn" : 16
"twice" : 16
"write" : 16
"afford" : 15
"ago" : 15
"alteration" : 15
"altogether" : 15
"aye" : 15
"cause" : 15
"considerable" : 15
"delay" : 15
"during" : 15
"duty" : 15
"engage" : 15
"exeter" : 15
"express" : 15
"expressed" : 15
"finding" : 15
"fire" : 15
"folly" : 15
"form" : 15
"gained" : 15
"highly" : 15
"imagine" : 15
"importance" : 15
"increased" : 15
"interesting" : 15
"itself" : 15
"lately" : 15
"match" : 15
"mutual" : 15
"note" : 15
"observed" : 15
"offer" : 15
"pleasant" : 15
"presence" : 15
"prevented" : 15
"prospect" : 15
"removed" : 15
"several" : 15
"six" : 15
"smart" : 15
"spoken" : 15
"suffering" : 15
"supported" : 15
"suspicion" : 15
"tea" : 15
"tomorrow" : 15
"trust" : 15
"turning" : 15
"twenty" : 15
"unwilling" : 15
"utmost" : 15
"violent" : 15
"whenever" : 15
"work" : 15
"amusement" : 14
"assistance" : 14
"assurance" : 14
"card" : 14
"cheerful" : 14
"clock" : 14
"command" : 14
"concerned" : 14
"consolation" : 14
"creature" : 14
"degree" : 14
"dreadful" : 14
"drew" : 14
"eagerly" : 14
"encouragement" : 14
"engagements" : 14
"frequently" : 14
"fresh" : 14
"heavy" : 14
"inconvenience" : 14
"instead" : 14
"invited" : 14
"judged" : 14
"justice" : 14
"knows" : 14
"mama" : 14
"marrying" : 14
"meaning" : 14
"mention" : 14
"news" : 14
"occurred" : 14
"perceive" : 14
"politeness" : 14
"proof" : 14
"propriety" : 14
"relation" : 14
"reproach" : 14
"respectable" : 14
"rose" : 14
"selfish" : 14
"seven" : 14
"sit" : 14
"suffer" : 14
"support" : 14
"treated" : 14
"understood" : 14
"wishing" : 14
"won" : 14
"written" : 14
"yesterday" : 14
"yours" : 14
"approbation" : 13
"assist" : 13
"astonished" : 13
"besides" : 13
"burst" : 13
"calling" : 13
"comparison" : 13
"confess" : 13
"conscience" : 13
"consent" : 13
"continual" : 13
"cousin" : 13
"dance" : 13
"death" : 13
"due" : 13
"earnestly" : 13
"employment" : 13
"evident" : 13
"evil" : 13
"expense" : 13
"expression" : 13
"extremely" : 13
"feared" : 13
"fellow" : 13
"forth" : 13
"fortnight" : 13
"garden" : 13
"grateful" : 13
"health" : 13
"horses" : 13
"intended" : 13
"laugh" : 13
"leisure" : 13
"merit" : 13
"mistress" : 13
"naturally" : 13
"o" : 13
"offence" : 13
"opposition" : 13
"orders" : 13
"parted" : 13
"perceived" : 13
"persuasion" : 13
"post" : 13
"pressed" : 13
"private" : 13
"probability" : 13
"proved" : 13
"receiving" : 13
"recovered" : 13
"reflection" : 13
"returning" : 13
"says" : 13
"secure" : 13
"sensible" : 13
"solicitude" : 13
"sweet" : 13
"trouble" : 13
"vanity" : 13
"walking" : 13
"acknowledge" : 12
"acknowledged" : 12
"affections" : 12
"angry" : 12
"bad" : 12
"beautiful" : 12
"bringing" : 12
"broken" : 12
"censure" : 12
"communication" : 12
"consciousness" : 12
"consideration" : 12
"couple" : 12
"dislike" : 12
"distance" : 12
"drawn" : 12
"enter" : 12
"excellent" : 12
"exclaimed" : 12
"explanation" : 12
"fact" : 12
"fell" : 12
"finished" : 12
"forgot" : 12
"gay" : 12
"greatly" : 12
"grief" : 12
"happen" : 12
"hastily" : 12
"heartily" : 12
"high" : 12
"hills" : 12
"hold" : 12
"ignorance" : 12
"illness" : 12
"imagination" : 12
"important" : 12
"increase" : 12
"interested" : 12
"intimate" : 12
"join" : 12
"lay" : 12
"length" : 12
"lively" : 12
"material" : 12
"minute" : 12
"miserable" : 12
"natured" : 12
"objection" : 12
"paid" : 12
"parsonage" : 12
"placed" : 12
"please" : 12
"prepared" : 12
"probable" : 12
"procured" : 12
"promised" : 12
"raised" : 12
"reasonable" : 12
"related" : 12
"remain" : 12
"remaining" : 12
"resemblance" : 12
"restored" : 12
"sending" : 12
"sincere" : 12
"smiling" : 12
"spare" : 12
"sudden" : 12
"suddenly" : 12
"superior" : 12
"suspect" : 12
"terms" : 12
"tone" : 12
"unnecessary" : 12
"waiting" : 12
"warm" : 12
"warmly" : 12
"wretched" : 12
"wrote" : 12
"absence" : 11
"amazement" : 11
"anybody" : 11
"attempted" : 11
"attend" : 11
"beginning" : 11
"behaved" : 11
"caught" : 11
"choice" : 11
"colour" : 11
"concluded" : 11
"contrary" : 11
"dared" : 11
"deceived" : 11
"design" : 11
"eagerness" : 11
"employed" : 11
"established" : 11
"explained" : 11
"force" : 11
"forget" : 11
"free" : 11
"grey" : 11
"hurried" : 11
"ideas" : 11
"imprudence" : 11
"injured" : 11
"inquiries" : 11
"intimacy" : 11
"light" : 11
"magna" : 11
"monstrous" : 11
"objects" : 11
"openly" : 11
"parlour" : 11
"picture" : 11
"piece" : 11
"pleasing" : 11
"possession" : 11
"profession" : 11
"public" : 11
"rain" : 11
"raise" : 11
"recommended" : 11
"remembrance" : 11
"removal" : 11
"reply" : 11
"secrecy" : 11
"send" : 11
"sigh" : 11
"sooner" : 11
"sorrow" : 11
"spared" : 11
"spend" : 11
"stand" : 11
"stopped" : 11
"striking" : 11
"tender" : 11
"thank" : 11
"thoroughly" : 11
"uncertain" : 11
"valley" : 11
"variety" : 11
"village" : 11
"women" : 11
"wondered" : 11
"absolutely" : 10
"accept" : 10
"act" : 10
"admire" : 10
"advice" : 10
"along" : 10
"apology" : 10
"assurances" : 10
"attached" : 10
"attending" : 10
"ay" : 10
"beau" : 10
"beg" : 10
"books" : 10
"borne" : 10
"ceased" : 10
"condition" : 10
"delicacy" : 10
"depend" : 10
"dining" : 10
"direction" : 10
"dull" : 10
"education" : 10
"eight" : 10
"endeavouring" : 10
"fancied" : 10
"fears" : 10
"fifty" : 10
"following" : 10
"forgive" : 10
"forgiven" : 10
"fortitude" : 10
"furniture" : 10
"generally" : 10
"god" : 10
"harris" : 10
"hearted" : 10
"hers" : 10
"humour" : 10
"hurt" : 10
"indignation" : 10
"justify" : 10
"language" : 10
"lips" : 10
"lock" : 10
"lover" : 10
"lucky" : 10
"mamma" : 10
"miles" : 10
"mistake" : 10
"nay" : 10
"neighbourhood" : 10
"notion" : 10
"offered" : 10
"opened" : 10
"oxford" : 10
"palmers" : 10
"partiality" : 10
"parting" : 10
"proud" : 10
"quick" : 10
"readily" : 10
"reasonably" : 10
"request" : 10
"safe" : 10
"seated" : 10
"sensibility" : 10
"sentiments" : 10
"settle" : 10
"sleep" : 10
"speech" : 10
"stood" : 10
"story" : 10
"submit" : 10
"sum" : 10
"sunk" : 10
"third" : 10
"thrown" : 10
"uncomfortable" : 10
"united" : 10
"urged" : 10
"visitors" : 10
"waited" : 10
"watched" : 10
"wholly" : 10
"abilities" : 9
"abroad" : 9
"actions" : 9
"active" : 9
"advanced" : 9
"agreed" : 9
"ah" : 9
"arose" : 9
"around" : 9
"ashamed" : 9
"attempting" : 9
"beaux" : 9
"believing" : 9
"bestow" : 9
"catching" : 9
"chair" : 9
"charge" : 9
"clear" : 9
"close" : 9
"complexion" : 9
"concealed" : 9
"confined" : 9
"conscious" : 9
"continuance" : 9
"convince" : 9
"cruel" : 9
"dearest" : 9
"delicate" : 9
"depended" : 9
"described" : 9
"desirous" : 9
"determine" : 9
"dine" : 9
"direct" : 9
"distant" : 9
"doctor" : 9
"doubted" : 9
"draw" : 9
"embarrassment" : 9
"encouraging" : 9
"ended" : 9
"extraordinary" : 9
"fit" : 9
"frequent" : 9
"guess" : 9
"hard" : 9
"humoured" : 9
"impatient" : 9
"intentions" : 9
"introduced" : 9
"ladyship" : 9
"laid" : 9
"laughing" : 9
"learn" : 9
"listened" : 9
"maid" : 9
"matters" : 9
"merits" : 9
"motive" : 9
"moved" : 9
"observe" : 9
"odd" : 9
"offended" : 9
"pardon" : 9
"pay" : 9
"plainly" : 9
"pratt" : 9
"produce" : 9
"property" : 9
"quit" : 9
"ran" : 9
"reserve" : 9
"resist" : 9
"result" : 9
"satisfy" : 9
"seat" : 9
"separation" : 9
"servants" : 9
"service" : 9
"shocking" : 9
"sides" : 9
"sincerely" : 9
"slight" : 9
"softened" : 9
"sort" : 9
"spot" : 9
"started" : 9
"struck" : 9
"sufficient" : 9
"sussex" : 9
"telling" : 9
"today" : 9
"twelvemonth" : 9
"undoubtedly" : 9
"uneasiness" : 9
"unfortunately" : 9
"unpleasant" : 9
"advise" : 8
"affected" : 8
"agony" : 8
"alike" : 8
"amongst" : 8
"approve" : 8
"arranged" : 8
"assertion" : 8
"attentions" : 8
"belonging" : 8
"book" : 8
"bred" : 8
"buy" : 8
"calmly" : 8
"cards" : 8
"carrying" : 8
"changed" : 8
"comes" : 8
"commendation" : 8
"complete" : 8
"completely" : 8
"comprehend" : 8
"conceal" : 8
"concerns" : 8
"credit" : 8
"deny" : 8
"deserve" : 8
"died" : 8
"domestic" : 8
"earnestness" : 8
"effort" : 8
"elegant" : 8
"eliza" : 8
"england" : 8
"enjoy" : 8
"escape" : 8
"everybody" : 8
"excess" : 8
"existence" : 8
"explain" : 8
"fair" : 8
"figure" : 8
"fix" : 8
"gain" : 8
"gentle" : 8
"getting" : 8
"goodness" : 8
"ground" : 8
"grounds" : 8
"held" : 8
"hitherto" : 8
"horse" : 8
"hurry" : 8
"imagined" : 8
"improvement" : 8
"instant" : 8
"leaning" : 8
"learnt" : 8
"listening" : 8
"longstaple" : 8
"madam" : 8
"measure" : 8
"mere" : 8
"message" : 8
"morrow" : 8
"nearly" : 8
"number" : 8
"observing" : 8
"occur" : 8
"pass" : 8
"perfect" : 8
"performance" : 8
"persuade" : 8
"positive" : 8
"possibly" : 8
"presently" : 8
"pride" : 8
"proceeded" : 8
"prudence" : 8
"prudent" : 8
"recovery" : 8
"reflect" : 8
"regarded" : 8
"rendered" : 8
"resentment" : 8
"restless" : 8
"reward" : 8
"road" : 8
"safely" : 8
"secured" : 8
"seeking" : 8
"sentence" : 8
"setting" : 8
"shame" : 8
"shew" : 8
"similar" : 8
"sincerity" : 8
"single" : 8
"solitude" : 8
"somersetshire" : 8
"stop" : 8
"strength" : 8
"stronger" : 8
"strongly" : 8
"success" : 8
"supply" : 8
"supposing" : 8
"suspected" : 8
"thinks" : 8
"totally" : 8
"triumph" : 8
"trying" : 8
"unlike" : 8
"value" : 8
"venture" : 8
"visited" : 8
"visitor" : 8
"watching" : 8
"whisper" : 8
"accepted" : 7
"accommodation" : 7
"across" : 7
"acting" : 7
"add" : 7
"addition" : 7
"afforded" : 7
"altered" : 7
"amendment" : 7
"animated" : 7
"arise" : 7
"attentive" : 7
"avoided" : 7
"begged" : 7
"begin" : 7
"begun" : 7
"belief" : 7
"bestowed" : 7
"blow" : 7
"busy" : 7
"caution" : 7
"ceremony" : 7
"chaise" : 7
"chief" : 7
"chiefly" : 7
"chose" : 7
"church" : 7
"chuse" : 7
"claim" : 7
"coloured" : 7
"conduit" : 7
"considering" : 7
"continuing" : 7
"cruelty" : 7
"cut" : 7
"d" : 7
"decided" : 7
"declined" : 7
"departure" : 7
"dependence" : 7
"deserved" : 7
"discovered" : 7
"discovery" : 7
"distrust" : 7
"dread" : 7
"dress" : 7
"droll" : 7
"effects" : 7
"eligible" : 7
"elsewhere" : 7
"employments" : 7
"endeavoured" : 7
"entering" : 7
"entreaties" : 7
"escaped" : 7
"establishment" : 7
"excessively" : 7
"expenses" : 7
"farewell" : 7
"fate" : 7
"follow" : 7
"forgiveness" : 7
"founded" : 7
"friendly" : 7
"green" : 7
"grew" : 7
"guilt" : 7
"habit" : 7
"happier" : 7
"harry" : 7
"heaven" : 7
"hill" : 7
"hint" : 7
"honest" : 7
"idle" : 7
"impertinent" : 7
"impression" : 7
"improved" : 7
"improvements" : 7
"inclined" : 7
"independence" : 7
"independent" : 7
"indisposition" : 7
"inevitable" : 7
"insensible" : 7
"instance" : 7
"instrument" : 7
"invariably" : 7
"jealous" : 7
"joke" : 7
"lasted" : 7
"lead" : 7
"lessen" : 7
"liberality" : 7
"liked" : 7
"lives" : 7
"luckily" : 7
"materially" : 7
"nancy" : 7
"nearer" : 7
"nice" : 7
"noise" : 7
"objections" : 7
"offices" : 7
"oppressed" : 7
"owe" : 7
"owed" : 7
"paper" : 7
"partial" : 7
"passing" : 7
"patience" : 7
"paused" : 7
"peculiar" : 7
"period" : 7
"personal" : 7
"picturesque" : 7
"possibility" : 7
"poverty" : 7
"preference" : 7
"proceed" : 7
"prove" : 7
"provided" : 7
"quarter" : 7
"rate" : 7
"readiness" : 7
"reading" : 7
"reflections" : 7
"remove" : 7
"removing" : 7
"reserved" : 7
"residence" : 7
"ridiculous" : 7
"ring" : 7
"rising" : 7
"satisfactory" : 7
"selfishness" : 7
"seriously" : 7
"sex" : 7
"shewn" : 7
"shocked" : 7
"shop" : 7
"shortly" : 7
"show" : 7
"shut" : 7
"signify" : 7
"size" : 7
"smiled" : 7
"source" : 7
"speedily" : 7
"succeeded" : 7
"sufferings" : 7
"syllable" : 7
"tempt" : 7
"thanked" : 7
"thomas" : 7
"tolerably" : 7
"try" : 7
"unaccountable" : 7
"unhappiness" : 7
"vain" : 7
"valued" : 7
"vast" : 7
"voluntarily" : 7
"walks" : 7
"wealth" : 7
"williams" : 7
"willing" : 7
"winter" : 7
"youth" : 7
"accepting" : 6
"action" : 6
"actually" : 6
"admit" : 6
"adopt" : 6
"agree" : 6
"amends" : 6
"anne" : 6
"appearing" : 6
"arrangement" : 6
"asking" : 6
"assisted" : 6
"attractions" : 6
"bartlett" : 6
"basket" : 6
"beloved" : 6
"betrayed" : 6
"bound" : 6
"bow" : 6
"boy" : 6
"brief" : 6
"broke" : 6
"build" : 6
"c" : 6
"careful" : 6
"charms" : 6
"communicate" : 6
"communicated" : 6
"companions" : 6
"compliment" : 6
"confession" : 6
"confusion" : 6
"conjecture" : 6
"connected" : 6
"contempt" : 6
"convincing" : 6
"cordiality" : 6
"cost" : 6
"dearer" : 6
"declining" : 6
"degrees" : 6
"describe" : 6
"designs" : 6
"desirable" : 6
"discretion" : 6
"dissatisfied" : 6
"distinguished" : 6
"distressed" : 6
"divided" : 6
"dorsetshire" : 6
"downs" : 6
"drive" : 6
"dropped" : 6
"drove" : 6
"dwelling" : 6
"ear" : 6
"eat" : 6
"eighteen" : 6
"encouraged" : 6
"endeavour" : 6
"engaging" : 6
"enquire" : 6
"exchange" : 6
"excited" : 6
"exert" : 6
"expecting" : 6
"extent" : 6
"faint" : 6
"faith" : 6
"fall" : 6
"fast" : 6
"fatigue" : 6
"favourable" : 6
"fearful" : 6
"february" : 6
"finally" : 6
"foolish" : 6
"forgotten" : 6
"fully" : 6
"further" : 6
"gaiety" : 6
"game" : 6
"generosity" : 6
"gratifying" : 6
"gray" : 6
"grown" : 6
"happiest" : 6
"hereafter" : 6
"hopeless" : 6
"impatience" : 6
"improving" : 6
"inconstancy" : 6
"intention" : 6
"interrupted" : 6
"january" : 6
"judge" : 6
"justified" : 6
"la" : 6
"later" : 6
"liberal" : 6
"listen" : 6
"m" : 6
"maintained" : 6
"makes" : 6
"mark" : 6
"marked" : 6
"missed" : 6
"moreover" : 6
"motives" : 6
"needed" : 6
"nervous" : 6
"offend" : 6
"office" : 6
"pained" : 6
"passage" : 6
"patient" : 6
"perceiving" : 6
"performed" : 6
"pianoforte" : 6
"plymouth" : 6
"pocket" : 6
"points" : 6
"preceding" : 6
"preparation" : 6
"press" : 6
"pretend" : 6
"previously" : 6
"principles" : 6
"promote" : 6
"proposal" : 6
"punishment" : 6
"pursuits" : 6
"puzzled" : 6
"raillery" : 6
"reach" : 6
"reasons" : 6
"reception" : 6
"recollect" : 6
"recollecting" : 6
"red" : 6
"regrets" : 6
"rejoiced" : 6
"remark" : 6
"remarkably" : 6
"remarks" : 6
"ruin" : 6
"scheme" : 6
"school" : 6
"security" : 6
"severe" : 6
"shyness" : 6
"situations" : 6
"sorrows" : 6
"sought" : 6
"stopt" : 6
"strangers" : 6
"submitted" : 6
"succeeding" : 6
"surely" : 6
"suspense" : 6
"takes" : 6
"thanks" : 6
"tired" : 6
"tis" : 6
"total" : 6
"trusted" : 6
"twelve" : 6
"unceasing" : 6
"uncommonly" : 6
"unjust" : 6
"unkindness" : 6
"valuable" : 6
"ventured" : 6
"views" : 6
"walls" : 6
"wanting" : 6
"whitwell" : 6
"wind" : 6
"wine" : 6
"wit" : 6
"younger" : 6
"abode" : 5
"accident" : 5
"accidentally" : 5
"accounts" : 5
"acknowledging" : 5
"admired" : 5
"admitted" : 5
"advisable" : 5
"also" : 5
"although" : 5
"anger" : 5
"announce" : 5
"aside" : 5
"attach" : 5
"attribute" : 5
"bent" : 5
"betraying" : 5
"blame" : 5
"bless" : 5
"blessing" : 5
"blind" : 5
"blushed" : 5
"bond" : 5
"born" : 5
"breach" : 5
"breaking" : 5
"breeding" : 5
"building" : 5
"buildings" : 5
"bye" : 5
"calculated" : 5
"cares" : 5
"carry" : 5
"cast" : 5
"cease" : 5
"checked" : 5
"claims" : 5
"clever" : 5
"coldness" : 5
"collected" : 5
"comfortably" : 5
"compassionate" : 5
"complacency" : 5
"complaint" : 5
"concealing" : 5
"concealment" : 5
"conceive" : 5
"conclusion" : 5
"confinement" : 5
"congratulate" : 5
"connections" : 5
"constancy" : 5
"constantly" : 5
"contradicted" : 5
"convenience" : 5
"covered" : 5
"crying" : 5
"dancing" : 5
"dawlish" : 5
"declaration" : 5
"deep" : 5
"deeply" : 5
"deficient" : 5
"delivered" : 5
"demands" : 5
"denied" : 5
"desired" : 5
"difficult" : 5
"dined" : 5
"discover" : 5
"disgrace" : 5
"dismissed" : 5
"disposal" : 5
"disturb" : 5
"disturbed" : 5
"donavan" : 5
"doubts" : 5
"dressing" : 5
"dying" : 5
"earth" : 5
"eloquence" : 5
"enable" : 5
"enquiries" : 5
"enquiry" : 5
"entreat" : 5
"entreaty" : 5
"events" : 5
"examination" : 5
"excessive" : 5
"exercise" : 5
"expectations" : 5
"expensive" : 5
"exposed" : 5
"extended" : 5
"falsehood" : 5
"fashion" : 5
"fault" : 5
"features" : 5
"felicity" : 5
"fever" : 5
"fifteen" : 5
"filled" : 5
"firmness" : 5
"fitted" : 5
"flattered" : 5
"flattering" : 5
"flattery" : 5
"forlorn" : 5
"formerly" : 5
"forte" : 5
"fortunately" : 5
"frank" : 5
"fright" : 5
"frightened" : 5
"front" : 5
"gate" : 5
"generous" : 5
"gentlemen" : 5
"gentleness" : 5
"glance" : 5
"goes" : 5
"gracious" : 5
"gravity" : 5
"grieving" : 5
"growing" : 5
"guided" : 5
"guilty" : 5
"hanging" : 5
"harm" : 5
"hesitation" : 5
"housekeeper" : 5
"houses" : 5
"hysterics" : 5
"ignorant" : 5
"impertinence" : 5
"impropriety" : 5
"improve" : 5
"imputed" : 5
"increasing" : 5
"induced" : 5
"inform" : 5
"injustice" : 5
"inquire" : 5
"integrity" : 5
"introduce" : 5
"inviting" : 5
"involved" : 5
"jenning" : 5
"justly" : 5
"land" : 5
"languid" : 5
"lasting" : 5
"line" : 5
"loud" : 5
"loves" : 5
"maids" : 5
"mansion" : 5
"middle" : 5
"misfortune" : 5
"month" : 5
"musical" : 5
"narrow" : 5
"newspaper" : 5
"nineteen" : 5
"noisy" : 5
"nurse" : 5
"obligation" : 5
"observations" : 5
"occasional" : 5
"occasioned" : 5
"offering" : 5
"opening" : 5
"openness" : 5
"ordinary" : 5
"overcame" : 5
"parent" : 5
"parts" : 5
"passion" : 5
"paying" : 5
"persuading" : 5
"piano" : 5
"play" : 5
"pointed" : 5
"preparing" : 5
"presented" : 5
"preserved" : 5
"prevail" : 5
"prevailed" : 5
"principle" : 5
"privilege" : 5
"promising" : 5
"properly" : 5
"purposely" : 5
"questions" : 5
"rapid" : 5
"raptures" : 5
"rational" : 5
"recollected" : 5
"regretting" : 5
"relating" : 5
"remembered" : 5
"repeat" : 5
"repetition" : 5
"reproof" : 5
"reverie" : 5
"risk" : 5
"rooms" : 5
"roused" : 5
"run" : 5
"sanguine" : 5
"saved" : 5
"scene" : 5
"schemes" : 5
"scruple" : 5
"season" : 5
"seeming" : 5
"seventeen" : 5
"shewing" : 5
"shock" : 5
"silently" : 5
"sink" : 5
"slightly" : 5
"sold" : 5
"sons" : 5
"sound" : 5
"speedy" : 5
"spirited" : 5
"spring" : 5
"sprung" : 5
"standing" : 5
"startled" : 5
"steady" : 5
"struggle" : 5
"stupid" : 5
"submission" : 5
"suited" : 5
"summer" : 5
"suspicions" : 5
"sympathy" : 5
"symptom" : 5
"tall" : 5
"temptation" : 5
"thankful" : 5
"thorough" : 5
"thoughtfulness" : 5
"tolerable" : 5
"toothpick" : 5
"torture" : 5
"touch" : 5
"travelled" : 5
"travelling" : 5
"treat" : 5
"treating" : 5
"treatment" : 5
"trees" : 5
"trifling" : 5
"unkind" : 5
"unknown" : 5
"unwillingness" : 5
"urge" : 5
"urgent" : 5
"usually" : 5
"vastly" : 5
"vexed" : 5
"warrant" : 5
"water" : 5
"weight" : 5
"whence" : 5
"white" : 5
"whither" : 5
"widow" : 5
"witness" : 5
"witnessed" : 5
"wondering" : 5
"woods" : 5
"working" : 5
"wound" : 5
"wretchedness" : 5
"abhorrence" : 4
"absurdity" : 4
"accompany" : 4
"acknowledgment" : 4
"acquit" : 4
"acted" : 4
"additional" : 4
"addressing" : 4
"advised" : 4
"affairs" : 4
"affecting" : 4
"allowance" : 4
"amount" : 4
"amuse" : 4
"animation" : 4
"announced" : 4
"announcing" : 4
"annuities" : 4
"annuity" : 4
"anxiously" : 4
"apartment" : 4
"apparently" : 4
"application" : 4
"appointment" : 4
"apprehensions" : 4
"approach" : 4
"arguments" : 4
"arms" : 4
"assent" : 4
"astonishing" : 4
"attaching" : 4
"attendance" : 4
"attitude" : 4
"attributed" : 4
"authority" : 4
"awakened" : 4
"beauties" : 4
"begging" : 4
"behave" : 4
"benefit" : 4
"betty" : 4
"bid" : 4
"board" : 4
"bore" : 4
"bowed" : 4
"boys" : 4
"carefully" : 4
"careless" : 4
"careys" : 4
"carriages" : 4
"certainty" : 4
"characters" : 4
"check" : 4
"china" : 4
"civilities" : 4
"clothes" : 4
"coach" : 4
"collect" : 4
"colouring" : 4
"comforts" : 4
"commission" : 4
"compliments" : 4
"composed" : 4
"comprehension" : 4
"conducted" : 4
"conjectures" : 4
"conquest" : 4
"consented" : 4
"considerate" : 4
"contained" : 4
"contented" : 4
"contents" : 4
"continue" : 4
"correspondence" : 4
"counsel" : 4
"county" : 4
"courage" : 4
"court" : 4
"cowper" : 4
"curacy" : 4
"curricle" : 4
"daily" : 4
"dead" : 4
"deceitful" : 4
"deceive" : 4
"decide" : 4
"decision" : 4
"defend" : 4
"defer" : 4
"deficiency" : 4
"delayed" : 4
"dependent" : 4
"despair" : 4
"despatch" : 4
"detain" : 4
"determination" : 4
"devil" : 4
"devoted" : 4
"dignity" : 4
"directed" : 4
"dirty" : 4
"discussion" : 4
"displeased" : 4
"dispose" : 4
"disregarded" : 4
"distinction" : 4
"distinguish" : 4
"distresses" : 4
"diverted" : 4
"divide" : 4
"doubtful" : 4
"drawings" : 4
"dreaded" : 4
"driven" : 4
"driving" : 4
"dropt" : 4
"duties" : 4
"earlier" : 4
"earliest" : 4
"ears" : 4
"east" : 4
"elder" : 4
"elevated" : 4
"elliott" : 4
"employ" : 4
"encourage" : 4
"energy" : 4
"enjoyed" : 4
"error" : 4
"estimation" : 4
"examine" : 4
"examining" : 4
"exclamation" : 4
"excursion" : 4
"expedient" : 4
"experience" : 4
"experienced" : 4
"exquisite" : 4
"extreme" : 4
"exultation" : 4
"fail" : 4
"failed" : 4
"falling" : 4
"familiarity" : 4
"farm" : 4
"fettered" : 4
"finest" : 4
"firmly" : 4
"flatter" : 4
"fondly" : 4
"forbearance" : 4
"forcing" : 4
"foresee" : 4
"forming" : 4
"forms" : 4
"fortunate" : 4
"forty" : 4
"foundation" : 4
"fulfilled" : 4
"genius" : 4
"genteel" : 4
"genuine" : 4
"gift" : 4
"governed" : 4
"graceful" : 4
"gratefully" : 4
"guessed" : 4
"guest" : 4
"handkerchief" : 4
"happily" : 4
"hardened" : 4
"hasty" : 4
"height" : 4
"highest" : 4
"honestly" : 4
"honourable" : 4
"honoured" : 4
"hoping" : 4
"horrid" : 4
"horror" : 4
"human" : 4
"humility" : 4
"hung" : 4
"hunters" : 4
"husbands" : 4
"idleness" : 4
"implied" : 4
"impossibility" : 4
"inattention" : 4
"incapable" : 4
"inconveniences" : 4
"incumbent" : 4
"indisposed" : 4
"indulged" : 4
"indulgence" : 4
"inferior" : 4
"infinitely" : 4
"inquired" : 4
"insipidity" : 4
"insisted" : 4
"interval" : 4
"intimately" : 4
"invariable" : 4
"jokes" : 4
"lesser" : 4
"lie" : 4
"likes" : 4
"lose" : 4
"lovely" : 4
"lovers" : 4
"lowering" : 4
"measures" : 4
"mentioning" : 4
"merry" : 4
"method" : 4
"michaelmas" : 4
"mile" : 4
"mirth" : 4
"misapprehension" : 4
"misconduct" : 4
"mix" : 4
"moderate" : 4
"moving" : 4
"nearest" : 4
"neck" : 4
"needless" : 4
"neglect" : 4
"noble" : 4
"notes" : 4
"numerous" : 4
"offending" : 4
"oppose" : 4
"outward" : 4
"overlook" : 4
"pains" : 4
"pair" : 4
"pausing" : 4
"peace" : 4
"perplexity" : 4
"personally" : 4
"pitiable" : 4
"pitied" : 4
"plain" : 4
"plans" : 4
"pointer" : 4
"polite" : 4
"powers" : 4
"practice" : 4
"precious" : 4
"principal" : 4
"procure" : 4
"procuring" : 4
"prodigious" : 4
"professions" : 4
"promoting" : 4
"pronounced" : 4
"proofs" : 4
"proportion" : 4
"proposed" : 4
"prospects" : 4
"provision" : 4
"provoke" : 4
"pulse" : 4
"purchase" : 4
"pursuing" : 4
"pursuit" : 4
"putting" : 4
"quietly" : 4
"quitting" : 4
"raises" : 4
"rap" : 4
"rapidity" : 4
"rapturous" : 4
"recommendation" : 4
"reconciled" : 4
"regular" : 4
"relate" : 4
"relative" : 4
"release" : 4
"relieved" : 4
"remains" : 4
"reminded" : 4
"repair" : 4
"report" : 4
"resembled" : 4
"respecting" : 4
"reverse" : 4
"riches" : 4
"ride" : 4
"rival" : 4
"robbed" : 4
"romantic" : 4
"rubber" : 4
"rude" : 4
"ruined" : 4
"sacrifice" : 4
"sang" : 4
"satisfying" : 4
"scenes" : 4
"screens" : 4
"sell" : 4
"senses" : 4
"sentiment" : 4
"separate" : 4
"served" : 4
"severely" : 4
"sharing" : 4
"shewed" : 4
"shook" : 4
"shy" : 4
"sick" : 4
"sickly" : 4
"sighed" : 4
"simplicity" : 4
"situated" : 4
"sky" : 4
"slighted" : 4
"sly" : 4
"snug" : 4
"somehow" : 4
"song" : 4
"soothe" : 4
"spreading" : 4
"square" : 4
"subjects" : 4
"suggest" : 4
"suggested" : 4
"supper" : 4
"surrounding" : 4
"suspecting" : 4
"sweetness" : 4
"talents" : 4
"taught" : 4
"temple" : 4
"tendency" : 4
"tenderly" : 4
"terrible" : 4
"testimony" : 4
"tete" : 4
"thoughtful" : 4
"throw" : 4
"throwing" : 4
"timed" : 4
"tranquil" : 4
"tranquillity" : 4
"travel" : 4
"tree" : 4
"tricks" : 4
"truly" : 4
"turns" : 4
"twisted" : 4
"unanimous" : 4
"unconscious" : 4
"uneasy" : 4
"unexpected" : 4
"universally" : 4
"unless" : 4
"unpardonable" : 4
"unreserve" : 4
"unwelcome" : 4
"unworthy" : 4
"varying" : 4
"vexation" : 4
"vindication" : 4
"violence" : 4
"visiting" : 4
"visits" : 4
"wandering" : 4
"watch" : 4
"weakness" : 4
"weary" : 4
"welfare" : 4
"wherever" : 4
"wild" : 4
"winding" : 4
"wisest" : 4
"withdrew" : 4
"works" : 4
"youngest" : 4
"ability" : 3
"abruptly" : 3
"absent" : 3
"absolute" : 3
"abuse" : 3
"acceptable" : 3
"acceptance" : 3
"accommodate" : 3
"accordingly" : 3
"accustomary" : 3
"aches" : 3
"acknowledgments" : 3
"acquisition" : 3
"addressed" : 3
"admires" : 3
"admiring" : 3
"admitting" : 3
"advance" : 3
"advantageous" : 3
"advantages" : 3
"affect" : 3
"affectation" : 3
"affluence" : 3
"affording" : 3
"afternoon" : 3
"aid" : 3
"alarmed" : 3
"alluded" : 3
"aloud" : 3
"amply" : 3
"amused" : 3
"angel" : 3
"annamaria" : 3
"apologising" : 3
"apothecary" : 3
"applied" : 3
"approached" : 3
"approaching" : 3
"approved" : 3
"ardour" : 3
"argument" : 3
"arm" : 3
"arrangements" : 3
"asleep" : 3
"ate" : 3
"atonement" : 3
"attachments" : 3
"attack" : 3
"attentively" : 3
"attract" : 3
"attracted" : 3
"attraction" : 3
"authorised" : 3
"avail" : 3
"avoiding" : 3
"awful" : 3
"awkward" : 3
"baby" : 3
"bachelor" : 3
"balls" : 3
"banished" : 3
"becoming" : 3
"beheld" : 3
"benefited" : 3
"benevolence" : 3
"bestowing" : 3
"blamable" : 3
"blessed" : 3
"bloom" : 3
"boast" : 3
"bold" : 3
"brown" : 3
"built" : 3
"busily" : 3
"bustle" : 3
"candid" : 3
"cap" : 3
"captivating" : 3
"cases" : 3
"catch" : 3
"chamber" : 3
"chanced" : 3
"charm" : 3
"chat" : 3
"checking" : 3
"cheeks" : 3
"choose" : 3
"chusing" : 3
"cleared" : 3
"clearly" : 3
"closed" : 3
"clouds" : 3
"communicating" : 3
"comparatively" : 3
"compare" : 3
"comparisons" : 3
"competence" : 3
"complain" : 3
"complained" : 3
"compliance" : 3
"comprehended" : 3
"conceit" : 3
"concluding" : 3
"condemnation" : 3
"confessed" : 3
"confident" : 3
"confirm" : 3
"confirming" : 3
"conjectured" : 3
"consequent" : 3
"consoled" : 3
"constitution" : 3
"contentment" : 3
"contrast" : 3
"contrived" : 3
"convenient" : 3
"converse" : 3
"conversed" : 3
"conversing" : 3
"conveyed" : 3
"coolness" : 3
"corner" : 3
"counteract" : 3
"coxcomb" : 3
"created" : 3
"creatures" : 3
"crime" : 3
"cross" : 3
"crowd" : 3
"cunning" : 3
"dangerous" : 3
"debating" : 3
"decay" : 3
"decent" : 3
"declaring" : 3
"deeper" : 3
"defect" : 3
"defence" : 3
"dejection" : 3
"deliverance" : 3
"demand" : 3
"denial" : 3
"departed" : 3
"depends" : 3
"deprive" : 3
"deprived" : 3
"description" : 3
"desperate" : 3
"destroyed" : 3
"detest" : 3
"dictate" : 3
"diffident" : 3
"dignified" : 3
"disadvantage" : 3
"disappointments" : 3
"discharge" : 3
"discontent" : 3
"disgusted" : 3
"disliking" : 3
"display" : 3
"displayed" : 3
"displeasure" : 3
"dissuade" : 3
"dividing" : 3
"doctrine" : 3
"doors" : 3
"dreadfully" : 3
"dressed" : 3
"drink" : 3
"drinking" : 3
"dry" : 3
"earned" : 3
"eating" : 3
"ecstasy" : 3
"effusion" : 3
"elderly" : 3
"ellison" : 3
"enabled" : 3
"endure" : 3
"engrossed" : 3
"enjoying" : 3
"ensured" : 3
"errand" : 3
"erred" : 3
"evidently" : 3
"example" : 3
"exceeding" : 3
"exciting" : 3
"excused" : 3
"exertions" : 3
"exist" : 3
"existed" : 3
"expressing" : 3
"expressions" : 3
"expressive" : 3
"expressively" : 3
"extensive" : 3
"extravagance" : 3
"extravagant" : 3
"f" : 3
"false" : 3
"families" : 3
"fancying" : 3
"fashioned" : 3
"faultless" : 3
"faults" : 3
"faulty" : 3
"feet" : 3
"fervent" : 3
"fetch" : 3
"feverish" : 3
"filigree" : 3
"fingers" : 3
"finish" : 3
"firm" : 3
"fixing" : 3
"flannel" : 3
"flow" : 3
"fool" : 3
"formality" : 3
"fortunes" : 3
"frankness" : 3
"freedom" : 3
"frost" : 3
"fulfill" : 3
"gaining" : 3
"gardens" : 3
"gladly" : 3
"glass" : 3
"gloomy" : 3
"graciousness" : 3
"grand" : 3
"grandeur" : 3
"gravel" : 3
"gravely" : 3
"greatness" : 3
"guests" : 3
"guineas" : 3
"habits" : 3
"hastened" : 3
"hate" : 3
"heavens" : 3
"heightened" : 3
"heightening" : 3
"henry" : 3
"hesitated" : 3
"hints" : 3
"horrible" : 3
"horseback" : 3
"household" : 3
"humanity" : 3
"humble" : 3
"imaginary" : 3
"impatiently" : 3
"imprudent" : 3
"impulse" : 3
"indignant" : 3
"indispensable" : 3
"indulge" : 3
"indulgent" : 3
"indulging" : 3
"inevitably" : 3
"infirmity" : 3
"injury" : 3
"inn" : 3
"inquiring" : 3
"insolence" : 3
"intending" : 3
"intermission" : 3
"intervals" : 3
"introduction" : 3
"intrusion" : 3
"involuntary" : 3
"irresistible" : 3
"judging" : 3
"justification" : 3
"kissed" : 3
"knees" : 3
"landscape" : 3
"lane" : 3
"laughter" : 3
"lavender" : 3
"laying" : 3
"leading" : 3
"learned" : 3
"leaves" : 3
"legal" : 3
"lengthened" : 3
"lest" : 3
"library" : 3
"liking" : 3
"linen" : 3
"lines" : 3
"ll" : 3
"lodgings" : 3
"longed" : 3
"lot" : 3
"lower" : 3
"luck" : 3
"lying" : 3
"magnificent" : 3
"malice" : 3
"manly" : 3
"march" : 3
"marlborough" : 3
"meanness" : 3
"meditation" : 3
"meditations" : 3
"memory" : 3
"mildness" : 3
"modern" : 3
"modesty" : 3
"mothers" : 3
"mouth" : 3
"move" : 3
"narration" : 3
"necessarily" : 3
"neighbour" : 3
"neighbours" : 3
"nephew" : 3
"nicest" : 3
"niece" : 3
"notions" : 3
"obtain" : 3
"obtained" : 3
"occasions" : 3
"october" : 3
"offspring" : 3
"opposed" : 3
"oppression" : 3
"ordained" : 3
"order" : 3
"originated" : 3
"outlived" : 3
"outweigh" : 3
"painted" : 3
"pang" : 3
"papers" : 3
"parish" : 3
"payment" : 3
"pen" : 3
"penetration" : 3
"perceptible" : 3
"perform" : 3
"pitying" : 3
"placing" : 3
"plate" : 3
"playing" : 3
"pleasantly" : 3
"plenty" : 3
"posture" : 3
"praised" : 3
"pre" : 3
"prepare" : 3
"presentation" : 3
"pressing" : 3
"prettily" : 3
"prevailing" : 3
"previous" : 3
"principally" : 3
"print" : 3
"probabilities" : 3
"productive" : 3
"profess" : 3
"professedly" : 3
"progress" : 3
"prompted" : 3
"pronounce" : 3
"pronouncing" : 3
"protection" : 3
"provocation" : 3
"provoking" : 3
"pure" : 3
"pursued" : 3
"quarrel" : 3
"quickly" : 3
"rained" : 3
"rank" : 3
"rapidly" : 3
"rascal" : 3
"re" : 3
"reality" : 3
"recall" : 3
"recalled" : 3
"recovering" : 3
"reduced" : 3
"refused" : 3
"regarding" : 3
"regretted" : 3
"rejoice" : 3
"rejoicing" : 3
"relationship" : 3
"released" : 3
"relieve" : 3
"remembering" : 3
"rent" : 3
"repeatedly" : 3
"repeating" : 3
"represent" : 3
"represented" : 3
"requested" : 3
"require" : 3
"requires" : 3
"resisted" : 3
"resolute" : 3
"resolving" : 3
"respected" : 3
"respects" : 3
"restraint" : 3
"revealed" : 3
"reviving" : 3
"rewarded" : 3
"rid" : 3
"ridicule" : 3
"rise" : 3
"rob" : 3
"roof" : 3
"rouse" : 3
"rousing" : 3
"running" : 3
"rupture" : 3
"sacrificed" : 3
"sad" : 3
"sadly" : 3
"safety" : 3
"scissors" : 3
"scolded" : 3
"screams" : 3
"screen" : 3
"secretly" : 3
"securing" : 3
"seek" : 3
"seldom" : 3
"sensations" : 3
"separated" : 3
"series" : 3
"serve" : 3
"settling" : 3
"shade" : 3
"shan" : 3
"shared" : 3
"sharp" : 3
"shed" : 3
"skin" : 3
"sleepless" : 3
"slightest" : 3
"slow" : 3
"smallness" : 3
"solemnity" : 3
"solid" : 3
"solitary" : 3
"somebody" : 3
"somewhat" : 3
"soothing" : 3
"sportsman" : 3
"sportsmen" : 3
"stanhill" : 3
"steadiness" : 3
"steep" : 3
"stepping" : 3
"stirring" : 3
"stone" : 3
"strengthened" : 3
"stretched" : 3
"strictly" : 3
"strongest" : 3
"stubborn" : 3
"studied" : 3
"study" : 3
"subdued" : 3
"succession" : 3
"suitable" : 3
"sun" : 3
"supplied" : 3
"suspended" : 3
"talks" : 3
"tame" : 3
"task" : 3
"temporary" : 3
"terror" : 3
"thence" : 3
"thither" : 3
"threw" : 3
"throat" : 3
"thursday" : 3
"timber" : 3
"tonight" : 3
"topic" : 3
"torn" : 3
"trace" : 3
"trial" : 3
"troublesome" : 3
"tuesday" : 3
"unaffected" : 3
"unavoidable" : 3
"unconcern" : 3
"unfairly" : 3
"unfeeling" : 3
"unfit" : 3
"ungracious" : 3
"unlikely" : 3
"unluckily" : 3
"unlucky" : 3
"unobtrusive" : 3
"unprincipled" : 3
"unthought" : 3
"unwell" : 3
"vacant" : 3
"variation" : 3
"violently" : 3
"volume" : 3
"vulgar" : 3
"wandered" : 3
"wants" : 3
"weakened" : 3
"welcomed" : 3
"wept" : 3
"westons" : 3
"wet" : 3
"whispered" : 3
"wicked" : 3
"wildly" : 3
"william" : 3
"willoughbys" : 3
"windows" : 3
"wise" : 3
"wonderful" : 3
"wood" : 3
"worst" : 3
"worthless" : 3
"wounding" : 3
"wretchedly" : 3
"writer" : 3
"writes" : 3
"yards" : 3
"yearly" : 3
"yourselves" : 3
"abhorred" : 2
"absurd" : 2
"abundance" : 2
"accent" : 2
"accommodating" : 2
"accompanied" : 2
"accomplished" : 2
"accomplishment" : 2
"according" : 2
"aching" : 2
"acquiescence" : 2
"acquitted" : 2
"acts" : 2
"acuteness" : 2
"additions" : 2
"adieu" : 2
"adieus" : 2
"adjoining" : 2
"admittance" : 2
"adorned" : 2
"advancement" : 2
"advances" : 2
"advancing" : 2
"affability" : 2
"affable" : 2
"affectedly" : 2
"affectionately" : 2
"affront" : 2
"affronting" : 2
"agitated" : 2
"agonies" : 2
"agreement" : 2
"ailment" : 2
"aimed" : 2
"alacrity" : 2
"alarming" : 2
"alive" : 2
"allowable" : 2
"allowances" : 2
"allowing" : 2
"altar" : 2
"alter" : 2
"alternately" : 2
"ambition" : 2
"amusements" : 2
"ancient" : 2
"anew" : 2
"anguish" : 2
"animating" : 2
"annihilation" : 2
"answerable" : 2
"answering" : 2
"anticipated" : 2
"apartments" : 2
"apparent" : 2
"appearances" : 2
"appetite" : 2
"applying" : 2
"apprehension" : 2
"apprehensive" : 2
"arbour" : 2
"ardent" : 2
"arisen" : 2
"arranging" : 2
"arriving" : 2
"art" : 2
"artful" : 2
"article" : 2
"ascended" : 2
"ascertain" : 2
"ascertained" : 2
"aspect" : 2
"assembled" : 2
"assented" : 2
"assiduities" : 2
"assigned" : 2
"assuring" : 2
"atmosphere" : 2
"atone" : 2
"attainable" : 2
"attained" : 2
"attempts" : 2
"attendants" : 2
"attractive" : 2
"attributing" : 2
"audible" : 2
"authors" : 2
"autumn" : 2
"avarice" : 2
"avignon" : 2
"avowal" : 2
"awake" : 2
"backwardness" : 2
"barbarous" : 2
"bargain" : 2
"barouche" : 2
"bath" : 2
"bearing" : 2
"beautifully" : 2
"befell" : 2
"bell" : 2
"beneath" : 2
"bespeak" : 2
"bewitching" : 2
"bide" : 2
"bit" : 2
"bitter" : 2
"bitterly" : 2
"blessings" : 2
"blood" : 2
"bolder" : 2
"bottom" : 2
"breath" : 2
"brightness" : 2
"brilliant" : 2
"brings" : 2
"brow" : 2
"calls" : 2
"calmer" : 2
"canal" : 2
"candour" : 2
"carelessness" : 2
"carpet" : 2
"carries" : 2
"cautious" : 2
"ceasing" : 2
"censured" : 2
"centre" : 2
"chariot" : 2
"charity" : 2
"charmed" : 2
"cheated" : 2
"cheek" : 2
"cheerless" : 2
"cherished" : 2
"christian" : 2
"christmas" : 2
"circle" : 2
"closet" : 2
"coat" : 2
"colicky" : 2
"combat" : 2
"commanded" : 2
"commonest" : 2
"communicative" : 2
"compact" : 2
"comparative" : 2
"complaints" : 2
"complaisance" : 2
"compound" : 2
"concerning" : 2
"concessions" : 2
"conclude" : 2
"condemned" : 2
"condescend" : 2
"conference" : 2
"confirmation" : 2
"confirmed" : 2
"confused" : 2
"congratulations" : 2
"conjectural" : 2
"conquests" : 2
"conscientious" : 2
"consequences" : 2
"consequently" : 2
"considerations" : 2
"considers" : 2
"consistent" : 2
"consult" : 2
"consulted" : 2
"contemptuous" : 2
"contend" : 2
"content" : 2
"contenting" : 2
"contracted" : 2
"contraction" : 2
"contradict" : 2
"contributed" : 2
"contrition" : 2
"conveniences" : 2
"conveying" : 2
"copy" : 2
"cordially" : 2
"correct" : 2
"correspond" : 2
"cottages" : 2
"courted" : 2
"courting" : 2
"courtland" : 2
"covert" : 2
"cows" : 2
"create" : 2
"creditable" : 2
"crimsoned" : 2
"critical" : 2
"crooked" : 2
"cry" : 2
"cure" : 2
"damp" : 2
"dark" : 2
"darling" : 2
"dashing" : 2
"davies" : 2
"debt" : 2
"deceiving" : 2
"deception" : 2
"deciding" : 2
"declares" : 2
"decorum" : 2
"deed" : 2
"defects" : 2
"deference" : 2
"deficiencies" : 2
"deliberating" : 2
"departing" : 2
"depending" : 2
"derived" : 2
"descend" : 2
"deserts" : 2
"deserving" : 2
"desperately" : 2
"despise" : 2
"detail" : 2
"deviation" : 2
"differently" : 2
"dimensions" : 2
"diminution" : 2
"dinners" : 2
"dirt" : 2
"disagreeable" : 2
"disappeared" : 2
"disappoint" : 2
"disappointing" : 2
"disapprove" : 2
"discernment" : 2
"discharged" : 2
"disclosing" : 2
"discompose" : 2
"discontents" : 2
"discovering" : 2
"disgraceful" : 2
"disgust" : 2
"disgusting" : 2
"disinclination" : 2
"disinterested" : 2
"disliked" : 2
"dismounted" : 2
"dispirited" : 2
"disregard" : 2
"dissipated" : 2
"dissipation" : 2
"distinguishing" : 2
"distressing" : 2
"doomed" : 2
"doted" : 2
"doting" : 2
"doubting" : 2
"dr" : 2
"dried" : 2
"drop" : 2
"dullness" : 2
"dwelt" : 2
"easier" : 2
"easiest" : 2
"effectual" : 2
"effusions" : 2
"eligibility" : 2
"ellisons" : 2
"embarrassed" : 2
"endeavours" : 2
"endless" : 2
"endowed" : 2
"ends" : 2
"enforced" : 2
"engross" : 2
"enquiring" : 2
"ensued" : 2
"entertained" : 2
"enthusiasm" : 2
"enthusiastic" : 2
"entire" : 2
"entreated" : 2
"envy" : 2
"essential" : 2
"establish" : 2
"esteemed" : 2
"esteems" : 2
"estimating" : 2
"evenings" : 2
"eventually" : 2
"evils" : 2
"exact" : 2
"examined" : 2
"excellence" : 2
"excite" : 2
"exerted" : 2
"expects" : 2
"expeditiously" : 2
"experiencing" : 2
"explanations" : 2
"expose" : 2
"expressly" : 2
"exterior" : 2
"extremity" : 2
"exultingly" : 2
"eyed" : 2
"eyeing" : 2
"faithfully" : 2
"fallen" : 2
"falls" : 2
"familiarly" : 2
"farthest" : 2
"fashionable" : 2
"fastidious" : 2
"fatigued" : 2
"fatigues" : 2
"favourites" : 2
"feebleness" : 2
"feed" : 2
"feelingly" : 2
"feigned" : 2
"fetching" : 2
"fickle" : 2
"fill" : 2
"finishing" : 2
"firmer" : 2
"flatteries" : 2
"flew" : 2
"floor" : 2
"flower" : 2
"flutter" : 2
"folded" : 2
"follows" : 2
"foot" : 2
"footman" : 2
"forbidding" : 2
"forebodings" : 2
"forenoon" : 2
"foreseen" : 2
"foretold" : 2
"forfeit" : 2
"forgave" : 2
"formal" : 2
"formidable" : 2
"forwards" : 2
"fourteen" : 2
"fourth" : 2
"frame" : 2
"friday" : 2
"friendliness" : 2
"frugality" : 2
"fruit" : 2
"furnished" : 2
"gaily" : 2
"gazing" : 2
"gentility" : 2
"gentlemanlike" : 2
"glimpse" : 2
"gloom" : 2
"glowing" : 2
"gold" : 2
"goodwill" : 2
"gossip" : 2
"gout" : 2
"govern" : 2
"gown" : 2
"grace" : 2
"graces" : 2
"gradually" : 2
"granted" : 2
"gratification" : 2
"gratify" : 2
"grecian" : 2
"grieve" : 2
"grieved" : 2
"grievous" : 2
"groom" : 2
"grounded" : 2
"guard" : 2
"guarded" : 2
"guardian" : 2
"guardianship" : 2
"guarding" : 2
"gum" : 2
"gun" : 2
"hackneyed" : 2
"handed" : 2
"handsomer" : 2
"handsomest" : 2
"hanover" : 2
"happens" : 2
"hardship" : 2
"harmony" : 2
"harshly" : 2
"haste" : 2
"hastening" : 2
"hat" : 2
"hated" : 2
"heavily" : 2
"heighten" : 2
"helping" : 2
"hence" : 2
"hesitatingly" : 2
"hiding" : 2
"higher" : 2
"hindrance" : 2
"hinted" : 2
"holidays" : 2
"hollow" : 2
"honesty" : 2
"honiton" : 2
"honor" : 2
"horrors" : 2
"hot" : 2
"housekeeping" : 2
"housemaid" : 2
"hurrying" : 2
"hysterical" : 2
"illiberal" : 2
"illiterate" : 2
"imaginable" : 2
"imagining" : 2
"impartial" : 2
"imperfect" : 2
"imperfectly" : 2
"impertinently" : 2
"impetuous" : 2
"impudence" : 2
"incivility" : 2
"inclinations" : 2
"incomprehensible" : 2
"inconsiderable" : 2
"inconsistency" : 2
"incurring" : 2
"indecision" : 2
"indication" : 2
"indies" : 2
"indigence" : 2
"indispensably" : 2
"inducement" : 2
"ineligible" : 2
"inexcusable" : 2
"inexperienced" : 2
"infection" : 2
"infer" : 2
"inferiority" : 2
"infirm" : 2
"influenced" : 2
"inforced" : 2
"informing" : 2
"ingratitude" : 2
"inhabit" : 2
"inhabitants" : 2
"injunction" : 2
"injuries" : 2
"innocence" : 2
"innocent" : 2
"insincerity" : 2
"insinuations" : 2
"insipid" : 2
"insolent" : 2
"inspection" : 2
"inspire" : 2
"instruction" : 2
"insufficient" : 2
"insult" : 2
"insured" : 2
"intends" : 2
"intentionally" : 2
"interim" : 2
"internally" : 2
"interposed" : 2
"interrupt" : 2
"interruption" : 2
"interview" : 2
"intreat" : 2
"introducing" : 2
"invented" : 2
"invitations" : 2
"involuntarily" : 2
"irremediable" : 2
"irrepressible" : 2
"irreproachable" : 2
"irritable" : 2
"irritated" : 2
"issued" : 2
"jargon" : 2
"jealousies" : 2
"joint" : 2
"jointure" : 2
"joyful" : 2
"joyfully" : 2
"judgments" : 2
"kensington" : 2
"kill" : 2
"kindest" : 2
"kindly" : 2
"kiss" : 2
"kitchen" : 2
"lamentations" : 2
"landing" : 2
"lanes" : 2
"lap" : 2
"larger" : 2
"lastingly" : 2
"lawn" : 2
"leaf" : 2
"learning" : 2
"legacy" : 2
"lessened" : 2
"liable" : 2
"libertine" : 2
"likelihood" : 2
"limbs" : 2
"limited" : 2
"limits" : 2
"linger" : 2
"lingering" : 2
"lit" : 2
"lobby" : 2
"lodging" : 2
"longest" : 2
"lowered" : 2
"luxury" : 2
"maintenance" : 2
"mall" : 2
"managed" : 2
"mantel" : 2
"marriages" : 2
"mary" : 2
"maternal" : 2
"matrimony" : 2
"measuring" : 2
"mediation" : 2
"medicines" : 2
"meditated" : 2
"meetings" : 2
"mercy" : 2
"merest" : 2
"messenger" : 2
"midst" : 2
"minded" : 2
"miniature" : 2
"minuter" : 2
"mixing" : 2
"mode" : 2
"moderation" : 2
"modest" : 2
"momentary" : 2
"monday" : 2
"morality" : 2
"mortification" : 2
"mortified" : 2
"mortify" : 2
"mortifying" : 2
"motionless" : 2
"mulberry" : 2
"nameless" : 2
"names" : 2
"narrowly" : 2
"neat" : 2
"needle" : 2
"neglected" : 2
"negligence" : 2
"nerves" : 2
"nicety" : 2
"nights" : 2
"nobly" : 2
"noon" : 2
"noticed" : 2
"nourishment" : 2
"nursing" : 2
"oblige" : 2
"obliging" : 2
"obligingly" : 2
"observant" : 2
"obstacle" : 2
"occasionally" : 2
"occupied" : 2
"opportunities" : 2
"orator" : 2
"ordered" : 2
"ordination" : 2
"origin" : 2
"ourselves" : 2
"overcoming" : 2
"overpowered" : 2
"owned" : 2
"owner" : 2
"pace" : 2
"painting" : 2
"pale" : 2
"pall" : 2
"paragraph" : 2
"parliament" : 2
"peculiarly" : 2
"penitence" : 2
"penny" : 2
"per" : 2
"perfection" : 2
"performances" : 2
"performers" : 2
"permitted" : 2
"perpetual" : 2
"perplexed" : 2
"perseverance" : 2
"persisted" : 2
"perverseness" : 2
"phrase" : 2
"pieces" : 2
"pin" : 2
"plagued" : 2
"planning" : 2
"plantations" : 2
"played" : 2
"pleasures" : 2
"pointing" : 2
"porter" : 2
"portion" : 2
"positively" : 2
"possess" : 2
"possessed" : 2
"possessions" : 2
"poultry" : 2
"pour" : 2
"practices" : 2
"practise" : 2
"precaution" : 2
"precisely" : 2
"preferable" : 2
"preferment" : 2
"preferred" : 2
"prejudice" : 2
"prejudiced" : 2
"prepossession" : 2
"prescribed" : 2
"preserve" : 2
"pretence" : 2
"pretensions" : 2
"price" : 2
"prior" : 2
"privacy" : 2
"privately" : 2
"prohibited" : 2
"projecting" : 2
"promises" : 2
"promoted" : 2
"propensities" : 2
"propensity" : 2
"prosperity" : 2
"protege" : 2
"protest" : 2
"providing" : 2
"provoked" : 2
"pulled" : 2
"purchases" : 2
"putrid" : 2
"quarters" : 2
"quest" : 2
"quicker" : 2
"quieted" : 2
"quietness" : 2
"raising" : 2
"rambles" : 2
"rapture" : 2
"rapturously" : 2
"rated" : 2
"rationally" : 2
"receipt" : 2
"recent" : 2
"reciprocal" : 2
"recital" : 2
"reckoned" : 2
"recommend" : 2
"reconciliation" : 2
"recover" : 2
"rectory" : 2
"recurred" : 2
"referred" : 2
"reflecting" : 2
"refuse" : 2
"refusing" : 2
"rejected" : 2
"relied" : 2
"reluctance" : 2
"relying" : 2
"remarkable" : 2
"render" : 2
"renewed" : 2
"repent" : 2
"repentance" : 2
"repose" : 2
"representation" : 2
"reprimand" : 2
"reproached" : 2
"reproaching" : 2
"requiring" : 2
"requisite" : 2
"reside" : 2
"resided" : 2
"resigned" : 2
"resistance" : 2
"resolutely" : 2
"resolve" : 2
"respectful" : 2
"rested" : 2
"restore" : 2
"restrain" : 2
"restrained" : 2
"retain" : 2
"retained" : 2
"retirement" : 2
"retort" : 2
"revenge" : 2
"revive" : 2
"revived" : 2
"richardson" : 2
"richardsons" : 2
"richer" : 2
"rider" : 2
"robbing" : 2
"sadness" : 2
"sagacity" : 2
"saint" : 2
"sakes" : 2
"salutation" : 2
"satirical" : 2
"saucy" : 2
"scold" : 2
"scott" : 2
"scoundrel" : 2
"screamed" : 2
"searched" : 2
"seating" : 2
"seats" : 2
"seclude" : 2
"secrets" : 2
"sends" : 2
"sensation" : 2
"sentences" : 2
"september" : 2
"services" : 2
"severity" : 2
"shedding" : 2
"shelter" : 2
"shillings" : 2
"shoes" : 2
"shops" : 2
"shot" : 2
"shoulder" : 2
"shoulders" : 2
"showed" : 2
"showery" : 2
"showing" : 2
"shrubberies" : 2
"shrubbery" : 2
"sickness" : 2
"sighted" : 2
"sign" : 2
"significantly" : 2
"silenced" : 2
"silly" : 2
"simply" : 2
"sixteen" : 2
"sketch" : 2
"slept" : 2
"slowly" : 2
"slumber" : 2
"smaller" : 2
"smiles" : 2
"smooth" : 2
"sobs" : 2
"soft" : 2
"soften" : 2
"sole" : 2
"solemn" : 2
"solemnly" : 2
"solicitous" : 2
"somewhere" : 2
"sophia" : 2
"sources" : 2
"south" : 2
"space" : 2
"spacious" : 2
"sparkling" : 2
"sparks" : 2
"speaks" : 2
"species" : 2
"specimen" : 2
"spiritless" : 2
"spoil" : 2
"sport" : 2
"sporting" : 2
"spread" : 2
"stable" : 2
"stage" : 2
"staid" : 2
"staircase" : 2
"starting" : 2
"starved" : 2
"stayed" : 2
"step" : 2
"steps" : 2
"stockings" : 2
"stolen" : 2
"stout" : 2
"straight" : 2
"streets" : 2
"strict" : 2
"strictest" : 2
"strike" : 2
"strikingly" : 2
"stuff" : 2
"subdue" : 2
"subjection" : 2
"subsisted" : 2
"succeed" : 2
"suffice" : 2
"sufficiently" : 2
"suggesting" : 2
"suit" : 2
"summits" : 2
"summoned" : 2
"superiority" : 2
"supplication" : 2
"surpassing" : 2
"surrounded" : 2
"survey" : 2
"suspicious" : 2
"sweetest" : 2
"syllables" : 2
"symptoms" : 2
"taylor" : 2
"teach" : 2
"tedious" : 2
"tediousness" : 2
"tells" : 2
"tend" : 2
"tended" : 2
"tenderest" : 2
"tending" : 2
"theirs" : 2
"thin" : 2
"thoughtfully" : 2
"threatened" : 2
"tidings" : 2
"tied" : 2
"tithes" : 2
"tongue" : 2
"travellers" : 2
"trembled" : 2
"trifle" : 2
"trifled" : 2
"troubles" : 2
"truest" : 2
"trusting" : 2
"tumbling" : 2
"twilight" : 2
"ugly" : 2
"unanswerable" : 2
"uncertainty" : 2
"unchanged" : 2
"uncheerful" : 2
"uncommon" : 2
"undecided" : 2
"undertake" : 2
"undiscerning" : 2
"unfavourable" : 2
"ungenerous" : 2
"ungrateful" : 2
"uniformly" : 2
"uniting" : 2
"unjustifiable" : 2
"unkindly" : 2
"unnatural" : 2
"unpleasantness" : 2
"unpleasing" : 2
"unreasonable" : 2
"unreserved" : 2
"unrestrained" : 2
"unsuitable" : 2
"unusual" : 2
"unwillingly" : 2
"unwounded" : 2
"urging" : 2
"useful" : 2
"using" : 2
"utter" : 2
"various" : 2
"vehemence" : 2
"vent" : 2
"veracity" : 2
"viewing" : 2
"vigorous" : 2
"villain" : 2
"virtue" : 2
"visibly" : 2
"vivacity" : 2
"voices" : 2
"voluntary" : 2
"waistcoat" : 2
"wanton" : 2
"wasted" : 2
"watchful" : 2
"watchfulness" : 2
"ways" : 2
"weak" : 2
"weaken" : 2
"wealthy" : 2
"wear" : 2
"wednesday" : 2
"whist" : 2
"whoever" : 2
"wildness" : 2
"willingness" : 2
"wisdom" : 2
"withhold" : 2
"withstood" : 2
"wives" : 2
"wore" : 2
"worldly" : 2
"worn" : 2
"worried" : 2
"wronged" : 2
"yew" : 2
"yield" : 2
"youthful" : 2
"zeal" : 2
"zealous" : 2
"abandoned" : 1
"abatement" : 1
"abbeyland" : 1
"abhor" : 1
"ablest" : 1
"abominably" : 1
"abounded" : 1
"abridge" : 1
"abridgement" : 1
"abruptness" : 1
"abstracted" : 1
"abstraction" : 1
"abstruse" : 1
"abundantly" : 1
"abused" : 1
"abuses" : 1
"acacia" : 1
"accelerate" : 1
"accents" : 1
"acceptably" : 1
"accidental" : 1
"accidently" : 1
"accommodations" : 1
"accordant" : 1
"accosted" : 1
"accounted" : 1
"accrue" : 1
"accurately" : 1
"accusation" : 1
"accuse" : 1
"accustom" : 1
"acquaintances" : 1
"acquiesced" : 1
"acquired" : 1
"acquitting" : 1
"actual" : 1
"acute" : 1
"acutely" : 1
"adapted" : 1
"adding" : 1
"addresses" : 1
"adequate" : 1
"adhering" : 1
"adjusting" : 1
"administer" : 1
"administering" : 1
"admirable" : 1
"admirers" : 1
"admission" : 1
"adopted" : 1
"affects" : 1
"affirmative" : 1
"affixed" : 1
"afflict" : 1
"afflicted" : 1
"afflicting" : 1
"afflictions" : 1
"afterward" : 1
"ages" : 1
"aggrandizement" : 1
"aggravation" : 1
"agitate" : 1
"agreeing" : 1
"ailments" : 1
"aim" : 1
"alarms" : 1
"alienated" : 1
"alighted" : 1
"alleged" : 1
"alleviation" : 1
"alloy" : 1
"allusion" : 1
"alphabet" : 1
"alterations" : 1
"altering" : 1
"alternative" : 1
"amazing" : 1
"amazingly" : 1
"amended" : 1
"amiably" : 1
"amidst" : 1
"amiss" : 1
"amounted" : 1
"ample" : 1
"amusing" : 1
"angrily" : 1
"ankle" : 1
"ankles" : 1
"annexed" : 1
"annum" : 1
"answers" : 1
"anticipate" : 1
"anticipating" : 1
"anticipation" : 1
"anticipations" : 1
"anymore" : 1
"apiece" : 1
"apologies" : 1
"apologize" : 1
"apologized" : 1
"appeal" : 1
"appeased" : 1
"appetites" : 1
"applauded" : 1
"appointed" : 1
"apprehended" : 1
"appropriate" : 1
"apricot" : 1
"april" : 1
"aptitude" : 1
"archness" : 1
"argue" : 1
"army" : 1
"arrive" : 1
"arrives" : 1
"articulate" : 1
"articulation" : 1
"artificial" : 1
"artless" : 1
"artlessness" : 1
"ascending" : 1
"ash" : 1
"assemblies" : 1
"asserted" : 1
"assertions" : 1
"assiduous" : 1
"assisting" : 1
"associate" : 1
"associating" : 1
"assuage" : 1
"astray" : 1
"asunder" : 1
"atoned" : 1
"atoning" : 1
"attacked" : 1
"attacks" : 1
"attendant" : 1
"audacity" : 1
"auditors" : 1
"augment" : 1
"augmented" : 1
"augmenting" : 1
"aunt" : 1
"auspicious" : 1
"auspiciously" : 1
"austen" : 1
"author" : 1
"availed" : 1
"await" : 1
"awaited" : 1
"awaken" : 1
"awakening" : 1
"awaking" : 1
"awhile" : 1
"awkwardness" : 1
"awoke" : 1
"backwards" : 1
"badness" : 1
"bags" : 1
"ball" : 1
"band" : 1
"banditti" : 1
"banish" : 1
"bank" : 1
"banker" : 1
"banns" : 1
"barbarously" : 1
"barouches" : 1
"bashful" : 1
"basis" : 1
"bathed" : 1
"beamed" : 1
"bears" : 1
"beasts" : 1
"beat" : 1
"bedchamber" : 1
"bedroom" : 1
"bedrooms" : 1
"beds" : 1
"bee" : 1
"beef" : 1
"befall" : 1
"befallen" : 1
"befalls" : 1
"begins" : 1
"behold" : 1
"beholding" : 1
"beings" : 1
"believes" : 1
"belonged" : 1
"belongs" : 1
"below" : 1
"bely" : 1
"benefactress" : 1
"beneficial" : 1
"benevolent" : 1
"benignant" : 1
"bequeath" : 1
"bequeathed" : 1
"bequest" : 1
"beset" : 1
"bespoke" : 1
"betray" : 1
"bias" : 1
"biased" : 1
"bidding" : 1
"biddy" : 1
"bigger" : 1
"billiard" : 1
"billiards" : 1
"bind" : 1
"birth" : 1
"bishop" : 1
"bitch" : 1
"bitterness" : 1
"black" : 1
"blackest" : 1
"blackguard" : 1
"blameable" : 1
"blamed" : 1
"blameless" : 1
"blank" : 1
"blast" : 1
"blasted" : 1
"blights" : 1
"blinded" : 1
"blindly" : 1
"bliss" : 1
"blockhead" : 1
"blooming" : 1
"blossoms" : 1
"blown" : 1
"blue" : 1
"blunder" : 1
"blundered" : 1
"blunt" : 1
"bluntly" : 1
"blush" : 1
"blushes" : 1
"blushing" : 1
"bluster" : 1
"boasting" : 1
"bodily" : 1
"boiled" : 1
"boisterous" : 1
"boldly" : 1
"bones" : 1
"bonnet" : 1
"bonomi" : 1
"booksellers" : 1
"borrow" : 1
"borrowed" : 1
"bottoms" : 1
"bout" : 1
"bowing" : 1
"bowling" : 1
"boyish" : 1
"branch" : 1
"branched" : 1
"braving" : 1
"break" : 1
"breakfasting" : 1
"breast" : 1
"breathing" : 1
"breed" : 1
"bribing" : 1
"briefly" : 1
"bright" : 1
"brightened" : 1
"brighter" : 1
"brilliancy" : 1
"bristol" : 1
"broad" : 1
"broader" : 1
"brood" : 1
"brooding" : 1
"brothers" : 1
"bruised" : 1
"brush" : 1
"bulk" : 1
"burgess" : 1
"burnt" : 1
"bursts" : 1
"bury" : 1
"butcher" : 1
"buying" : 1
"calculate" : 1
"calculation" : 1
"calming" : 1
"candidly" : 1
"candlelight" : 1
"candles" : 1
"cant" : 1
"canvassing" : 1
"capability" : 1
"caprice" : 1
"captivate" : 1
"carefulness" : 1
"carelessly" : 1
"caresses" : 1
"caressing" : 1
"caricature" : 1
"cartwright" : 1
"casement" : 1
"cash" : 1
"casino" : 1
"cassino" : 1
"casts" : 1
"cats" : 1
"caused" : 1
"cautiously" : 1
"cautiousness" : 1
"cavil" : 1
"ceiling" : 1
"celebrated" : 1
"celebration" : 1
"centered" : 1
"certainties" : 1
"cessation" : 1
"chagrined" : 1
"chained" : 1
"chairs" : 1
"chambers" : 1
"changes" : 1
"changing" : 1
"chaperon" : 1
"charged" : 1
"chatty" : 1
"cheap" : 1
"cheat" : 1
"cheered" : 1
"cheerfuller" : 1
"cherishing" : 1
"cherries" : 1
"chicken" : 1
"chimney" : 1
"choked" : 1
"chosen" : 1
"chuckle" : 1
"circles" : 1
"circuit" : 1
"circumspection" : 1
"circumstanced" : 1
"city" : 1
"civilly" : 1
"claimed" : 1
"claiming" : 1
"clamorous" : 1
"clapped" : 1
"clarke" : 1
"classed" : 1
"clearer" : 1
"clearing" : 1
"clemency" : 1
"clergyman" : 1
"clerk" : 1
"climate" : 1
"climbing" : 1
"clogged" : 1
"closely" : 1
"closer" : 1
"closing" : 1
"cloud" : 1
"club" : 1
"clue" : 1
"coachmaker" : 1
"coachman" : 1
"coats" : 1
"cod" : 1
"coffee" : 1
"coincide" : 1
"colder" : 1
"collation" : 1
"collecting" : 1
"collection" : 1
"columella" : 1
"comer" : 1
"comforted" : 1
"comforter" : 1
"comings" : 1
"commands" : 1
"commended" : 1
"comment" : 1
"comments" : 1
"commercial" : 1
"commiseration" : 1
"commissioned" : 1
"commonly" : 1
"companionableness" : 1
"compared" : 1
"compares" : 1
"compass" : 1
"complaining" : 1
"completed" : 1
"completion" : 1
"compliant" : 1
"complicated" : 1
"composedly" : 1
"composition" : 1
"comprise" : 1
"comprised" : 1
"compromise" : 1
"compunction" : 1
"conceited" : 1
"concerto" : 1
"concession" : 1
"conciliate" : 1
"conciliation" : 1
"concise" : 1
"conclusions" : 1
"concurrence" : 1
"condemning" : 1
"conditioned" : 1
"conditions" : 1
"condolence" : 1
"confederacy" : 1
"confessedly" : 1
"confidant" : 1
"confidante" : 1
"confidential" : 1
"confiding" : 1
"conform" : 1
"conforming" : 1
"conformity" : 1
"confound" : 1
"confounded" : 1
"confusedly" : 1
"congratulated" : 1
"congratulating" : 1
"conjecturing" : 1
"conjure" : 1
"conjurer" : 1
"connect" : 1
"conning" : 1
"connoisseur" : 1
"connoisseurship" : 1
"conscientiously" : 1
"considerably" : 1
"considerately" : 1
"consisted" : 1
"consistency" : 1
"consists" : 1
"conspicuous" : 1
"conspired" : 1
"constantia" : 1
"consternation" : 1
"constitutional" : 1
"constrained" : 1
"construction" : 1
"consultation" : 1
"consumption" : 1
"containing" : 1
"contemptible" : 1
"contemptuously" : 1
"continually" : 1
"continuation" : 1
"contradictory" : 1
"contrasted" : 1
"contribute" : 1
"contributing" : 1
"contribution" : 1
"contrivance" : 1
"contrives" : 1
"contriving" : 1
"control" : 1
"controlled" : 1
"conveniently" : 1
"conversations" : 1
"convert" : 1
"cool" : 1
"copied" : 1
"copying" : 1
"cordial" : 1
"cordials" : 1
"correctness" : 1
"cote" : 1
"couched" : 1
"cough" : 1
"counsellor" : 1
"counter" : 1
"counteracted" : 1
"countless" : 1
"couples" : 1
"courtesy" : 1
"covenant" : 1
"covering" : 1
"coxcombs" : 1
"cramps" : 1
"creating" : 1
"creation" : 1
"credulous" : 1
"crept" : 1
"cries" : 1
"criminal" : 1
"critique" : 1
"crossing" : 1
"crossness" : 1
"crowned" : 1
"cruelly" : 1
"cultivated" : 1
"curate" : 1
"curious" : 1
"curtsying" : 1
"cutlets" : 1
"cutting" : 1
"dagger" : 1
"daggers" : 1
"dairy" : 1
"danced" : 1
"dances" : 1
"dares" : 1
"darker" : 1
"dartford" : 1
"date" : 1
"dawdled" : 1
"dawdling" : 1
"dawned" : 1
"dealt" : 1
"dearly" : 1
"debate" : 1
"debated" : 1
"debts" : 1
"decease" : 1
"decently" : 1
"decisions" : 1
"decisive" : 1
"decisively" : 1
"decline" : 1
"decrease" : 1
"decree" : 1
"deemed" : 1
"deepest" : 1
"defective" : 1
"defended" : 1
"define" : 1
"defined" : 1
"defy" : 1
"degrade" : 1
"degraded" : 1
"dejected" : 1
"delays" : 1
"deliberate" : 1
"deliberation" : 1
"delicacies" : 1
"delighful" : 1
"delightfully" : 1
"delineated" : 1
"delirium" : 1
"deliver" : 1
"delivery" : 1
"demanded" : 1
"demeanor" : 1
"demesne" : 1
"demonstrations" : 1
"demur" : 1
"demure" : 1
"dennison" : 1
"denote" : 1
"denoted" : 1
"denoting" : 1
"depart" : 1
"deplorable" : 1
"depravity" : 1
"depressed" : 1
"derive" : 1
"descendant" : 1
"describing" : 1
"deserted" : 1
"desertion" : 1
"deserves" : 1
"desiring" : 1
"despatching" : 1
"desperation" : 1
"despised" : 1
"despising" : 1
"despondence" : 1
"desponding" : 1
"dessert" : 1
"destination" : 1
"destiny" : 1
"destroy" : 1
"destroys" : 1
"destruction" : 1
"detaining" : 1
"detected" : 1
"detecting" : 1
"detection" : 1
"deter" : 1
"determinate" : 1
"determining" : 1
"deterred" : 1
"detestably" : 1
"detested" : 1
"detract" : 1
"devolved" : 1
"diabolical" : 1
"diction" : 1
"dies" : 1
"differed" : 1
"differing" : 1
"diffuse" : 1
"dilatoriness" : 1
"diminished" : 1
"directing" : 1
"directions" : 1
"disagreement" : 1
"disagreements" : 1
"disapprobation" : 1
"disapproved" : 1
"disapproves" : 1
"disapproving" : 1
"disarm" : 1
"disastrous" : 1
"disbelief" : 1
"discarded" : 1
"discern" : 1
"discerning" : 1
"discharging" : 1
"disclaiming" : 1
"disclosure" : 1
"discomposed" : 1
"discontented" : 1
"discreet" : 1
"discrimination" : 1
"discussions" : 1
"disengaged" : 1
"disengagement" : 1
"disgraced" : 1
"dishonorable" : 1
"disinherited" : 1
"disinterestedness" : 1
"dismiss" : 1
"disobedient" : 1
"disorder" : 1
"disordered" : 1
"dispatch" : 1
"dispatched" : 1
"dispatches" : 1
"dispersed" : 1
"dispersing" : 1
"disposing" : 1
"disproportion" : 1
"dispute" : 1
"disputes" : 1
"disqualifications" : 1
"disquiet" : 1
"disrespectfully" : 1
"dissatisfaction" : 1
"dissembling" : 1
"dissent" : 1
"dissented" : 1
"dissimilar" : 1
"dissolving" : 1
"distractedly" : 1
"distrusts" : 1
"divine" : 1
"division" : 1
"divorce" : 1
"doat" : 1
"doatingly" : 1
"dog" : 1
"dogs" : 1
"dooming" : 1
"dotted" : 1
"doubly" : 1
"doubtingly" : 1
"doubtless" : 1
"douceur" : 1
"dove" : 1
"drain" : 1
"drains" : 1
"drawback" : 1
"draws" : 1
"dreading" : 1
"dream" : 1
"dreaming" : 1
"dresses" : 1
"drift" : 1
"drives" : 1
"drops" : 1
"drunk" : 1
"drury" : 1
"dryness" : 1
"duets" : 1
"duly" : 1
"dupe" : 1
"duration" : 1
"dwell" : 1
"earthly" : 1
"easter" : 1
"ebullition" : 1
"echoed" : 1
"eclat" : 1
"economical" : 1
"economically" : 1
"economy" : 1
"ecstatic" : 1
"edge" : 1
"editions" : 1
"edtions" : 1
"effected" : 1
"effecting" : 1
"effectually" : 1
"efficacy" : 1
"eighty" : 1
"ejaculation" : 1
"elect" : 1
"election" : 1
"eloping" : 1
"elucidation" : 1
"eluded" : 1
"em" : 1
"embellishment" : 1
"embellishments" : 1
"embitter" : 1
"embraced" : 1
"embraces" : 1
"emergence" : 1
"emergency" : 1
"emigrant" : 1
"eminence" : 1
"emphasis" : 1
"emptiness" : 1
"enamoured" : 1
"enclosure" : 1
"encouragements" : 1
"encroachments" : 1
"encumbered" : 1
"endear" : 1
"endeavor" : 1
"endeavoring" : 1
"endeavors" : 1
"ending" : 1
"endurance" : 1
"endured" : 1
"enemy" : 1
"enfeebled" : 1
"enforcement" : 1
"enforcing" : 1
"enfranchisement" : 1
"enjoyments" : 1
"enlarge" : 1
"enlargement" : 1
"enlightened" : 1
"ennui" : 1
"enormously" : 1
"enquired" : 1
"enraged" : 1
"enrich" : 1
"entanglement" : 1
"entertain" : 1
"entertainment" : 1
"entitled" : 1
"entrusted" : 1
"entry" : 1
"enumeration" : 1
"environs" : 1
"epicurism" : 1
"equality" : 1
"equalled" : 1
"equals" : 1
"ere" : 1
"errors" : 1
"esq" : 1
"establishing" : 1
"esteeming" : 1
"estimable" : 1
"estimate" : 1
"estranged" : 1
"eternal" : 1
"etiquette" : 1
"everlasting" : 1
"evidence" : 1
"evince" : 1
"exactness" : 1
"exceed" : 1
"exceeded" : 1
"excellencies" : 1
"excepting" : 1
"exchanged" : 1
"exclaim" : 1
"exclaiming" : 1
"exclamations" : 1
"exclusively" : 1
"excursive" : 1
"excuses" : 1
"execution" : 1
"exercised" : 1
"exercising" : 1
"exhausted" : 1
"exhilarated" : 1
"exhilaration" : 1
"exigence" : 1
"exorbitant" : 1
"expand" : 1
"expatiate" : 1
"expediency" : 1
"expel" : 1
"expensiveness" : 1
"explanatory" : 1
"extend" : 1
"extending" : 1
"external" : 1
"extinction" : 1
"extinguished" : 1
"extolling" : 1
"extort" : 1
"extorted" : 1
"extorting" : 1
"extremest" : 1
"exuberance" : 1
"faces" : 1
"facts" : 1
"faded" : 1
"failing" : 1
"failure" : 1
"fainter" : 1
"fainting" : 1
"faintness" : 1
"fairer" : 1
"fairly" : 1
"faithful" : 1
"fame" : 1
"familiar" : 1
"familiarized" : 1
"famous" : 1
"fanciful" : 1
"fascinating" : 1
"faster" : 1
"fat" : 1
"fates" : 1
"fatiguing" : 1
"fearing" : 1
"feather" : 1
"feature" : 1
"feeble" : 1
"feebly" : 1
"feeding" : 1
"feels" : 1
"felicitations" : 1
"female" : 1
"females" : 1
"feminine" : 1
"fertile" : 1
"festival" : 1
"fetches" : 1
"field" : 1
"final" : 1
"finds" : 1
"finger" : 1
"fir" : 1
"fish" : 1
"flaring" : 1
"fled" : 1
"flourish" : 1
"flourishing" : 1
"flowed" : 1
"flowing" : 1
"fluctuating" : 1
"flushed" : 1
"fly" : 1
"foibles" : 1
"fondness" : 1
"food" : 1
"foolishly" : 1
"footsteps" : 1
"forbade" : 1
"forbear" : 1
"forbid" : 1
"forbidden" : 1
"forbore" : 1
"forcibly" : 1
"forego" : 1
"foregoing" : 1
"foreplanned" : 1
"foresaw" : 1
"foreseeing" : 1
"foresight" : 1
"foretell" : 1
"forfeited" : 1
"forfeiting" : 1
"forgetting" : 1
"formally" : 1
"forsaking" : 1
"forwarded" : 1
"forwarding" : 1
"foundations" : 1
"fourteenth" : 1
"fowls" : 1
"fox" : 1
"frantic" : 1
"freeze" : 1
"frequency" : 1
"fretful" : 1
"fretted" : 1
"friendliest" : 1
"frighten" : 1
"frightens" : 1
"frightful" : 1
"frivolous" : 1
"froid" : 1
"frosts" : 1
"fruitless" : 1
"fulfil" : 1
"fullest" : 1
"funeral" : 1
"furnishing" : 1
"fury" : 1
"fuss" : 1
"gales" : 1
"gallantry" : 1
"galling" : 1
"gallop" : 1
"gape" : 1
"gardener" : 1
"garret" : 1
"garrets" : 1
"gates" : 1
"gathered" : 1
"gathering" : 1
"gaucherie" : 1
"gaze" : 1
"generations" : 1
"generously" : 1
"genial" : 1
"genteelly" : 1
"gently" : 1
"genuinely" : 1
"gibson" : 1
"giddy" : 1
"giggling" : 1
"gigs" : 1
"gilberts" : 1
"gives" : 1
"glances" : 1
"glebe" : 1
"gloominess" : 1
"gloried" : 1
"gloves" : 1
"glow" : 1
"godby" : 1
"goings" : 1
"goodby" : 1
"governing" : 1
"gowns" : 1
"gracefulness" : 1
"grandmothers" : 1
"grass" : 1
"grate" : 1
"grievance" : 1
"grieves" : 1
"gross" : 1
"group" : 1
"grows" : 1
"grudge" : 1
"guardians" : 1
"guessing" : 1
"guidance" : 1
"guide" : 1
"habitation" : 1
"habitual" : 1
"hall" : 1
"hallooing" : 1
"halves" : 1
"ham" : 1
"hamlet" : 1
"handle" : 1
"handsomely" : 1
"hang" : 1
"hanger" : 1
"happening" : 1
"harbour" : 1
"hardening" : 1
"hardily" : 1
"hardness" : 1
"hardships" : 1
"harmless" : 1
"harp" : 1
"hartshorn" : 1
"hateful" : 1
"hates" : 1
"hating" : 1
"haughty" : 1
"hauteur" : 1
"hazard" : 1
"hazarded" : 1
"hazarding" : 1
"hazy" : 1
"headache" : 1
"headed" : 1
"heads" : 1
"headstrong" : 1
"healing" : 1
"healthful" : 1
"healthy" : 1
"hearer" : 1
"hears" : 1
"heartiness" : 1
"hearts" : 1
"hearty" : 1
"heat" : 1
"heath" : 1
"heights" : 1
"heir" : 1
"heirs" : 1
"helpless" : 1
"helpmate" : 1
"henceforth" : 1
"henceforward" : 1
"hens" : 1
"henshawe" : 1
"hero" : 1
"heroically" : 1
"heroism" : 1
"hilarity" : 1
"hinder" : 1
"history" : 1
"hit" : 1
"hither" : 1
"ho" : 1
"hoarded" : 1
"holborn" : 1
"holburn" : 1
"holding" : 1
"holds" : 1
"homes" : 1
"hon" : 1
"honeysuckles" : 1
"honorable" : 1
"honorably" : 1
"honourably" : 1
"honours" : 1
"hop" : 1
"horizon" : 1
"horridly" : 1
"hospitable" : 1
"hospitality" : 1
"hostess" : 1
"hostile" : 1
"howsever" : 1
"hue" : 1
"hum" : 1
"humbled" : 1
"humiliating" : 1
"humiliations" : 1
"humored" : 1
"humouring" : 1
"hunt" : 1
"hunted" : 1
"hunts" : 1
"hush" : 1
"hussy" : 1
"huswifes" : 1
"ice" : 1
"identify" : 1
"idled" : 1
"idolized" : 1
"ii" : 1
"illaudable" : 1
"illusion" : 1
"illustration" : 1
"image" : 1
"imagery" : 1
"imaginations" : 1
"imbibed" : 1
"imitate" : 1
"imminent" : 1
"immoderately" : 1
"immovable" : 1
"immoveable" : 1
"imparted" : 1
"impartiality" : 1
"impediment" : 1
"impenetrable" : 1
"imperfection" : 1
"imperfections" : 1
"implies" : 1
"imply" : 1
"impolitic" : 1
"importunate" : 1
"importunity" : 1
"impose" : 1
"impoverished" : 1
"impoverishing" : 1
"impracticable" : 1
"imprint" : 1
"improperly" : 1
"improvident" : 1
"imprudently" : 1
"impudently" : 1
"inadvertence" : 1
"inarticulate" : 1
"inattentive" : 1
"incautiousness" : 1
"incessant" : 1
"incessantly" : 1
"inch" : 1
"incitement" : 1
"inclosing" : 1
"included" : 1
"including" : 1
"incoherently" : 1
"incommode" : 1
"incommoded" : 1
"incompatible" : 1
"inconsiderately" : 1
"inconsolable" : 1
"inconstant" : 1
"inconvenient" : 1
"incredulity" : 1
"incurable" : 1
"incurred" : 1
"indecorous" : 1
"indefatigable" : 1
"indelicacy" : 1
"independently" : 1
"indignantly" : 1
"indignity" : 1
"indisputable" : 1
"indistinct" : 1
"individual" : 1
"indolence" : 1
"indolent" : 1
"indubitable" : 1
"induce" : 1
"ineffectual" : 1
"inelegant" : 1
"inexperience" : 1
"infamous" : 1
"infamously" : 1
"infancy" : 1
"infant" : 1
"infants" : 1
"infatuation" : 1
"inflict" : 1
"inflicted" : 1
"inflicting" : 1
"inforce" : 1
"ingenious" : 1
"ingenuity" : 1
"ingratiating" : 1
"inhabited" : 1
"inhabiting" : 1
"inherit" : 1
"inheriting" : 1
"inheritor" : 1
"injure" : 1
"innate" : 1
"inner" : 1
"innumerable" : 1
"inquietude" : 1
"inquisitive" : 1
"inquisitiveness" : 1
"insensibility" : 1
"insignificance" : 1
"insincere" : 1
"insist" : 1
"inspect" : 1
"inspired" : 1
"inspiring" : 1
"installed" : 1
"instantaneous" : 1
"instantaneously" : 1
"instigated" : 1
"instigation" : 1
"instructions" : 1
"insufferably" : 1
"insufficiency" : 1
"insulted" : 1
"insulting" : 1
"insurmountable" : 1
"intelligent" : 1
"intelligible" : 1
"intend" : 1
"intent" : 1
"intents" : 1
"intercourse" : 1
"interests" : 1
"interfere" : 1
"interference" : 1
"interfering" : 1
"interrupting" : 1
"interspersed" : 1
"interviews" : 1
"intimated" : 1
"intoxication" : 1
"intrinsically" : 1
"intruded" : 1
"intruder" : 1
"intruding" : 1
"intuitively" : 1
"invalid" : 1
"invaluable" : 1
"invent" : 1
"inventing" : 1
"invention" : 1
"inventive" : 1
"investigation" : 1
"invite" : 1
"involve" : 1
"irksome" : 1
"irrational" : 1
"irreconcilable" : 1
"irregular" : 1
"irreparable" : 1
"irresolute" : 1
"irritability" : 1
"irritates" : 1
"irritation" : 1
"ivory" : 1
"jacket" : 1
"james" : 1
"jane" : 1
"jealousy" : 1
"jest" : 1
"jewels" : 1
"jilting" : 1
"joining" : 1
"joked" : 1
"joking" : 1
"joys" : 1
"judicious" : 1
"judiciously" : 1
"jumbled" : 1
"justifying" : 1
"juvenile" : 1
"keen" : 1
"keeping" : 1
"keeps" : 1
"keys" : 1
"kicked" : 1
"kinder" : 1
"kingdom" : 1
"kingham" : 1
"kisses" : 1
"knack" : 1
"knave" : 1
"kneeling" : 1
"knives" : 1
"knocking" : 1
"knoll" : 1
"l" : 1
"labor" : 1
"labour" : 1
"laboured" : 1
"lain" : 1
"lament" : 1
"lamentation" : 1
"lamenting" : 1
"lamps" : 1
"landlord" : 1
"languages" : 1
"largest" : 1
"latest" : 1
"laudable" : 1
"laughs" : 1
"lawyer" : 1
"leagued" : 1
"leant" : 1
"lecture" : 1
"legacies" : 1
"leisurely" : 1
"lengths" : 1
"lessening" : 1
"lesson" : 1
"letting" : 1
"lief" : 1
"lies" : 1
"lifted" : 1
"lifting" : 1
"lightened" : 1
"lighter" : 1
"lightly" : 1
"likeness" : 1
"lingered" : 1
"lip" : 1
"liquor" : 1
"listener" : 1
"literature" : 1
"liveliness" : 1
"livings" : 1
"local" : 1
"lodges" : 1
"loitered" : 1
"lombardy" : 1
"loose" : 1
"losing" : 1
"lounging" : 1
"loving" : 1
"lowness" : 1
"lurking" : 1
"lustily" : 1
"luxurious" : 1
"mab" : 1
"madness" : 1
"magnanimity" : 1
"malady" : 1
"malevolence" : 1
"malignant" : 1
"manage" : 1
"management" : 1
"manager" : 1
"mankind" : 1
"manor" : 1
"mantelpiece" : 1
"mare" : 1
"marking" : 1
"marmalade" : 1
"marries" : 1
"martha" : 1
"mass" : 1
"master" : 1
"maxim" : 1
"maxims" : 1
"meadows" : 1
"meal" : 1
"meals" : 1
"meantime" : 1
"meanwhile" : 1
"measured" : 1
"meat" : 1
"mechanically" : 1
"medicine" : 1
"medium" : 1
"memento" : 1
"memorable" : 1
"mend" : 1
"mental" : 1
"merited" : 1
"meritorious" : 1
"merrier" : 1
"merriment" : 1
"messages" : 1
"metaphor" : 1
"mid" : 1
"midsummer" : 1
"mighty" : 1
"mild" : 1
"militate" : 1
"militated" : 1
"mindful" : 1
"minds" : 1
"mingle" : 1
"minor" : 1
"minutely" : 1
"minuteness" : 1
"minutiae" : 1
"miracle" : 1
"misapplied" : 1
"mischievous" : 1
"misconstruction" : 1
"misinformed" : 1
"misled" : 1
"misses" : 1
"mistakes" : 1
"mistrust" : 1
"misunderstood" : 1
"moan" : 1
"modestest" : 1
"mohrs" : 1
"moiety" : 1
"monkey" : 1
"monopolize" : 1
"mood" : 1
"moonlight" : 1
"mornings" : 1
"mosquitoes" : 1
"moss" : 1
"motherly" : 1
"motion" : 1
"mound" : 1
"mountain" : 1
"mounted" : 1
"mourning" : 1
"muff" : 1
"murmurings" : 1
"muslin" : 1
"muttered" : 1
"mutton" : 1
"mutually" : 1
"mysterious" : 1
"mysteriously" : 1
"mystery" : 1
"nabobs" : 1
"named" : 1
"naming" : 1
"narrator" : 1
"nasty" : 1
"navy" : 1
"necessitous" : 1
"negative" : 1
"negligent" : 1
"negotiation" : 1
"neighbouring" : 1
"neighbourly" : 1
"nerve" : 1
"nests" : 1
"nettles" : 1
"newer" : 1
"newly" : 1
"newness" : 1
"newspapers" : 1
"newton" : 1
"nieces" : 1
"niggardly" : 1
"nine" : 1
"ninny" : 1
"nipped" : 1
"nobleman" : 1
"nodded" : 1
"nodding" : 1
"nods" : 1
"noisier" : 1
"nominal" : 1
"nonsense" : 1
"nonsensical" : 1
"norfolk" : 1
"northward" : 1
"noticing" : 1
"nought" : 1
"novel" : 1
"novelty" : 1
"november" : 1
"nt" : 1
"nuisance" : 1
"nuncheon" : 1
"nurses" : 1
"oath" : 1
"obedient" : 1
"obey" : 1
"obeyed" : 1
"objected" : 1
"obligations" : 1
"observable" : 1
"observer" : 1
"obstacles" : 1
"obstinacy" : 1
"obstinate" : 1
"obstructed" : 1
"obtaining" : 1
"obviated" : 1
"obviating" : 1
"occupation" : 1
"occupations" : 1
"occupy" : 1
"occurrence" : 1
"oddest" : 1
"odious" : 1
"offences" : 1
"officious" : 1
"officiously" : 1
"oftener" : 1
"oftenest" : 1
"older" : 1
"oldest" : 1
"olives" : 1
"omitted" : 1
"ones" : 1
"oneself" : 1
"opera" : 1
"opposite" : 1
"option" : 1
"original" : 1
"ornament" : 1
"ornamented" : 1
"ornaments" : 1
"orphan" : 1
"ours" : 1
"outdone" : 1
"outgrown" : 1
"outraged" : 1
"outrun" : 1
"outside" : 1
"outstaid" : 1
"outstretched" : 1
"outstripped" : 1
"outwardly" : 1
"outweighs" : 1
"overheard" : 1
"overlooked" : 1
"overpowering" : 1
"overspreading" : 1
"overstrained" : 1
"owners" : 1
"owning" : 1
"p" : 1
"paces" : 1
"pacified" : 1
"packages" : 1
"packed" : 1
"page" : 1
"pages" : 1
"painfully" : 1
"paint" : 1
"painter" : 1
"palanquins" : 1
"paleness" : 1
"palm" : 1
"pangs" : 1
"panting" : 1
"parcels" : 1
"pardonable" : 1
"parents" : 1
"parlors" : 1
"parrys" : 1
"particularity" : 1
"partly" : 1
"partners" : 1
"partook" : 1
"passages" : 1
"passionate" : 1
"passionately" : 1
"passions" : 1
"pasturage" : 1
"pasture" : 1
"patches" : 1
"path" : 1
"patron" : 1
"patronage" : 1
"patroness" : 1
"patronised" : 1
"pattern" : 1
"patterns" : 1
"pearls" : 1
"pecuniary" : 1
"pencil" : 1
"penetrate" : 1
"penitent" : 1
"penury" : 1
"perfections" : 1
"performing" : 1
"permission" : 1
"permit" : 1
"permitting" : 1
"persecution" : 1
"persecutions" : 1
"persevered" : 1
"persevering" : 1
"persisting" : 1
"persons" : 1
"perturbation" : 1
"perusal" : 1
"petty" : 1
"philanthropic" : 1
"philippic" : 1
"philosophic" : 1
"philosophy" : 1
"pictured" : 1
"pictures" : 1
"pillow" : 1
"pimples" : 1
"pinching" : 1
"pink" : 1
"pint" : 1
"pique" : 1
"piqued" : 1
"piquet" : 1
"pitch" : 1
"pitched" : 1
"plague" : 1
"plaguing" : 1
"plait" : 1
"plantation" : 1
"plants" : 1
"playfellows" : 1
"playful" : 1
"playfulness" : 1
"playthings" : 1
"plea" : 1
"plead" : 1
"pleasanter" : 1
"pleasantest" : 1
"pleasantness" : 1
"plighted" : 1
"plump" : 1
"plums" : 1
"pocketbook" : 1
"poignant" : 1
"pointedly" : 1
"pointers" : 1
"poking" : 1
"policy" : 1
"polished" : 1
"politely" : 1
"political" : 1
"politics" : 1
"ponds" : 1
"poorly" : 1
"pope" : 1
"poplars" : 1
"popt" : 1
"portman" : 1
"portrait" : 1
"position" : 1
"possesses" : 1
"possessing" : 1
"possessor" : 1
"postponing" : 1
"posts" : 1
"potent" : 1
"poured" : 1
"powered" : 1
"powerful" : 1
"powerfully" : 1
"practicable" : 1
"practiced" : 1
"practised" : 1
"praises" : 1
"prayers" : 1
"preceded" : 1
"precise" : 1
"precision" : 1
"prefer" : 1
"preferring" : 1
"prejudices" : 1
"premeditated" : 1
"premises" : 1
"prenticed" : 1
"preparations" : 1
"prepossessed" : 1
"prepossessing" : 1
"prescience" : 1
"prescriptions" : 1
"presenting" : 1
"presents" : 1
"preserver" : 1
"presided" : 1
"presume" : 1
"presumed" : 1
"pretended" : 1
"pretends" : 1
"pretext" : 1
"prettier" : 1
"prettiest" : 1
"preyed" : 1
"priory" : 1
"proclaim" : 1
"proclaimed" : 1
"proclaiming" : 1
"prodigiously" : 1
"producing" : 1
"production" : 1
"professed" : 1
"profited" : 1
"profiting" : 1
"project" : 1
"projection" : 1
"projects" : 1
"promontories" : 1
"promotion" : 1
"promptitude" : 1
"prophecies" : 1
"proportionately" : 1
"proportioned" : 1
"proposals" : 1
"propose" : 1
"proposition" : 1
"proprietor" : 1
"prose" : 1
"prosecution" : 1
"prosperous" : 1
"prosperously" : 1
"protect" : 1
"protestations" : 1
"protested" : 1
"provide" : 1
"provident" : 1
"provisions" : 1
"prudently" : 1
"pry" : 1
"publication" : 1
"publishing" : 1
"pull" : 1
"punctual" : 1
"punctuality" : 1
"punish" : 1
"pupil" : 1
"puppies" : 1
"puppy" : 1
"puppyism" : 1
"purity" : 1
"purposes" : 1
"purse" : 1
"pursue" : 1
"puts" : 1
"puzzle" : 1
"qualification" : 1
"qualifications" : 1
"qualified" : 1
"quarrelled" : 1
"quarrelling" : 1
"queen" : 1
"quickened" : 1
"quickest" : 1
"quivered" : 1
"rage" : 1
"ranging" : 1
"ranked" : 1
"rapacious" : 1
"rare" : 1
"rascally" : 1
"rash" : 1
"reaching" : 1
"reanimate" : 1
"reaped" : 1
"reasonableness" : 1
"reasoning" : 1
"reasonings" : 1
"recently" : 1
"reckons" : 1
"reclaim" : 1
"reclining" : 1
"recognised" : 1
"recognition" : 1
"recommending" : 1
"reconcile" : 1
"reconsider" : 1
"recreating" : 1
"rectitude" : 1
"recurrence" : 1
"redeem" : 1
"referring" : 1
"refinement" : 1
"refinements" : 1
"reflected" : 1
"reform" : 1
"reformed" : 1
"refrain" : 1
"refreshed" : 1
"refreshment" : 1
"refreshments" : 1
"refusal" : 1
"regain" : 1
"regards" : 1
"regiment" : 1
"regularity" : 1
"regulate" : 1
"regulated" : 1
"relapse" : 1
"relatives" : 1
"relent" : 1
"reliance" : 1
"relics" : 1
"religion" : 1
"relinquished" : 1
"relish" : 1
"reluctantly" : 1
"remainder" : 1
"remedies" : 1
"remedy" : 1
"remembers" : 1
"remembrances" : 1
"remind" : 1
"reminding" : 1
"reminds" : 1
"remorse" : 1
"removes" : 1
"rendering" : 1
"renewal" : 1
"renewing" : 1
"renounced" : 1
"repaid" : 1
"repaired" : 1
"reparation" : 1
"repine" : 1
"repining" : 1
"replace" : 1
"replying" : 1
"reports" : 1
"representations" : 1
"representing" : 1
"repressed" : 1
"reproaches" : 1
"reproachfully" : 1
"reprobate" : 1
"reproved" : 1
"reproving" : 1
"repulsed" : 1
"repulsive" : 1
"reputation" : 1
"requesting" : 1
"rescued" : 1
"reseated" : 1
"resembling" : 1
"resented" : 1
"reservedness" : 1
"resettled" : 1
"residing" : 1
"residue" : 1
"resisting" : 1
"resists" : 1
"resorted" : 1
"resources" : 1
"respectability" : 1
"respectably" : 1
"respectfully" : 1
"respective" : 1
"restorative" : 1
"restoring" : 1
"restraints" : 1
"restriction" : 1
"resume" : 1
"resumed" : 1
"resuscitation" : 1
"retailed" : 1
"retarded" : 1
"retired" : 1
"retreat" : 1
"retreated" : 1
"retreating" : 1
"retrenched" : 1
"revealment" : 1
"reverted" : 1
"revival" : 1
"rheumatic" : 1
"rheumatism" : 1
"rheumatisms" : 1
"ribbons" : 1
"richard" : 1
"ridge" : 1
"riding" : 1
"rightly" : 1
"ringing" : 1
"rings" : 1
"risen" : 1
"rises" : 1
"risking" : 1
"rivals" : 1
"roads" : 1
"roared" : 1
"rocks" : 1
"rolling" : 1
"romance" : 1
"rooted" : 1
"rub" : 1
"rug" : 1
"rugged" : 1
"ruins" : 1
"ruling" : 1
"rumour" : 1
"rung" : 1
"rushed" : 1
"rushing" : 1
"sackville" : 1
"sacred" : 1
"sacrificing" : 1
"safeguard" : 1
"sagaciously" : 1
"sail" : 1
"sale" : 1
"sallow" : 1
"sally" : 1
"salmon" : 1
"saloon" : 1
"salts" : 1
"sandersons" : 1
"sashes" : 1
"saturday" : 1
"sauntered" : 1
"save" : 1
"saves" : 1
"savings" : 1
"scale" : 1
"scanty" : 1
"scattered" : 1
"scenery" : 1
"score" : 1
"scorn" : 1
"scornfully" : 1
"scorning" : 1
"scotland" : 1
"scrape" : 1
"scratch" : 1
"scratching" : 1
"scrawls" : 1
"screened" : 1
"scrupled" : 1
"scruples" : 1
"scrupling" : 1
"scrupulous" : 1
"scrutinies" : 1
"seal" : 1
"sealed" : 1
"search" : 1
"seasons" : 1
"seclusion" : 1
"seconded" : 1
"seconds" : 1
"secures" : 1
"sedateness" : 1
"seduced" : 1
"seducer" : 1
"seduction" : 1
"sedulously" : 1
"seized" : 1
"seizure" : 1
"sellers" : 1
"sensibly" : 1
"sensitive" : 1
"separately" : 1
"separations" : 1
"servilely" : 1
"sha" : 1
"shades" : 1
"shake" : 1
"shaken" : 1
"shakespeare" : 1
"shamefully" : 1
"shameless" : 1
"shape" : 1
"sharpe" : 1
"sheath" : 1
"sheet" : 1
"shews" : 1
"shield" : 1
"shift" : 1
"shivering" : 1
"shooting" : 1
"shorten" : 1
"shortness" : 1
"showers" : 1
"shown" : 1
"shrewd" : 1
"shrugging" : 1
"shuddering" : 1
"shuffling" : 1
"shutter" : 1
"shutters" : 1
"shutting" : 1
"sighing" : 1
"significancy" : 1
"significant" : 1
"signs" : 1
"silencing" : 1
"silk" : 1
"silks" : 1
"similarity" : 1
"simpered" : 1
"simpering" : 1
"simplest" : 1
"simpson" : 1
"sin" : 1
"sing" : 1
"singing" : 1
"singly" : 1
"sisterly" : 1
"sixpence" : 1
"slighter" : 1
"slighting" : 1
"slightingly" : 1
"slope" : 1
"sloping" : 1
"slyly" : 1
"smartness" : 1
"smirked" : 1
"smitten" : 1
"smokes" : 1
"smoothly" : 1
"sneer" : 1
"sobbed" : 1
"sober" : 1
"sobered" : 1
"sociable" : 1
"sofa" : 1
"softener" : 1
"soldier" : 1
"solely" : 1
"solicitation" : 1
"solicitations" : 1
"solidly" : 1
"somerset" : 1
"sometime" : 1
"songs" : 1
"sooth" : 1
"soothings" : 1
"sore" : 1
"sorrowful" : 1
"souls" : 1
"sounds" : 1
"soured" : 1
"sourness" : 1
"spasm" : 1
"speculation" : 1
"speculative" : 1
"speed" : 1
"spending" : 1
"spends" : 1
"splendidly" : 1
"spoiling" : 1
"spoilt" : 1
"spontaneous" : 1
"spotted" : 1
"sprained" : 1
"spraining" : 1
"spunging" : 1
"spurned" : 1
"st" : 1
"stake" : 1
"stammered" : 1
"standard" : 1
"stare" : 1
"stared" : 1
"stares" : 1
"start" : 1
"stated" : 1
"statement" : 1
"stating" : 1
"station" : 1
"stationer" : 1
"steadfast" : 1
"steadier" : 1
"steadily" : 1
"stealing" : 1
"steepest" : 1
"stepped" : 1
"sterling" : 1
"stew" : 1
"steward" : 1
"stiffly" : 1
"stimulated" : 1
"sting" : 1
"stipulate" : 1
"stirred" : 1
"stock" : 1
"stocks" : 1
"stole" : 1
"stomach" : 1
"stopping" : 1
"store" : 1
"storm" : 1
"stormy" : 1
"strains" : 1
"strangeness" : 1
"stranger" : 1
"streamed" : 1
"strengthen" : 1
"strengthening" : 1
"stress" : 1
"stretch" : 1
"strikes" : 1
"string" : 1
"strive" : 1
"striving" : 1
"stroke" : 1
"struggled" : 1
"struggling" : 1
"studies" : 1
"stuffed" : 1
"stupified" : 1
"stupor" : 1
"styled" : 1
"stylish" : 1
"submissive" : 1
"submitting" : 1
"subsequent" : 1
"subservient" : 1
"subsist" : 1
"subsisting" : 1
"substance" : 1
"successful" : 1
"successfully" : 1
"successively" : 1
"succour" : 1
"sufferer" : 1
"suffers" : 1
"sugar" : 1
"suggestion" : 1
"suitor" : 1
"summons" : 1
"sunday" : 1
"sunshine" : 1
"superannuated" : 1
"superintend" : 1
"supplanted" : 1
"supplying" : 1
"supports" : 1
"supposition" : 1
"surfaces" : 1
"surpass" : 1
"surpassed" : 1
"surplice" : 1
"surprising" : 1
"surveying" : 1
"survived" : 1
"surviving" : 1
"suspects" : 1
"swallow" : 1
"swallowed" : 1
"sweep" : 1
"sweetly" : 1
"sweetmeats" : 1
"swell" : 1
"swelling" : 1
"swept" : 1
"swollen" : 1
"swoon" : 1
"sympathised" : 1
"sympathize" : 1
"systems" : 1
"tablecloth" : 1
"tables" : 1
"tale" : 1
"talent" : 1
"talker" : 1
"tallest" : 1
"tardy" : 1
"tasted" : 1
"tastes" : 1
"tattered" : 1
"taverns" : 1
"tax" : 1
"taxed" : 1
"teazed" : 1
"teazing" : 1
"tediously" : 1
"temperate" : 1
"tempers" : 1
"temporizing" : 1
"tempted" : 1
"tempting" : 1
"terminated" : 1
"termination" : 1
"test" : 1
"thankfully" : 1
"theft" : 1
"theme" : 1
"thick" : 1
"thickly" : 1
"thirds" : 1
"thirteen" : 1
"thistles" : 1
"thomson" : 1
"thorns" : 1
"thoughtless" : 1
"threatening" : 1
"threats" : 1
"thrill" : 1
"throughout" : 1
"thunderbolt" : 1
"thunderbolts" : 1
"tidy" : 1
"tiled" : 1
"tiptoe" : 1
"toilet" : 1
"toleration" : 1
"toned" : 1
"tore" : 1
"torment" : 1
"tormented" : 1
"torrent" : 1
"tortured" : 1
"touched" : 1
"toward" : 1
"tower" : 1
"traced" : 1
"tract" : 1
"traded" : 1
"trades" : 1
"traits" : 1
"tranquility" : 1
"tranquilize" : 1
"transact" : 1
"transacted" : 1
"transgressed" : 1
"transparency" : 1
"transport" : 1
"transporting" : 1
"treachery" : 1
"treasured" : 1
"tremour" : 1
"trials" : 1
"tribute" : 1
"trick" : 1
"tricked" : 1
"tricking" : 1
"tries" : 1
"trim" : 1
"triumphantly" : 1
"trivial" : 1
"troop" : 1
"truths" : 1
"tuition" : 1
"tumbled" : 1
"tuned" : 1
"turf" : 1
"turnpike" : 1
"twill" : 1
"twould" : 1
"unabated" : 1
"unaccountably" : 1
"unacknowledged" : 1
"unaffectedly" : 1
"unamiable" : 1
"unavailing" : 1
"unavoidably" : 1
"unawares" : 1
"unbiased" : 1
"unblemished" : 1
"unbounded" : 1
"unbroken" : 1
"unchanging" : 1
"uncivil" : 1
"unconcerned" : 1
"unconnected" : 1
"unconquerable" : 1
"uncordial" : 1
"uncouth" : 1
"undeceive" : 1
"undeceiving" : 1
"undergoing" : 1
"undergone" : 1
"undertaking" : 1
"undervalue" : 1
"undervalued" : 1
"undeserving" : 1
"undesignedly" : 1
"undesirable" : 1
"undivided" : 1
"undoubted" : 1
"undoubtingly" : 1
"undressed" : 1
"unembarrassed" : 1
"unemployed" : 1
"unequal" : 1
"unequivocal" : 1
"unexhilarating" : 1
"unexpectedly" : 1
"unexpressed" : 1
"unfair" : 1
"unfashionable" : 1
"unfatherly" : 1
"unfathomable" : 1
"unfeigned" : 1
"unfolded" : 1
"unforeseen" : 1
"unfulfilled" : 1
"ungenteel" : 1
"ungraciously" : 1
"unguarded" : 1
"uniform" : 1
"uninfluenced" : 1
"uninformed" : 1
"unintelligible" : 1
"unintentional" : 1
"uninteresting" : 1
"unison" : 1
"unite" : 1
"unitedly" : 1
"unites" : 1
"universal" : 1
"university" : 1
"unknowingly" : 1
"unlocked" : 1
"unlover" : 1
"unmoved" : 1
"unnoticed" : 1
"unobserved" : 1
"unobtrusiveness" : 1
"unpacked" : 1
"unpardoned" : 1
"unpleasantest" : 1
"unpremeditated" : 1
"unpromising" : 1
"unquiet" : 1
"unread" : 1
"unreasonably" : 1
"unremitting" : 1
"unresisted" : 1
"unsatiable" : 1
"unseen" : 1
"unsettle" : 1
"unshaken" : 1
"unsolicited" : 1
"unspeakable" : 1
"unsteady" : 1
"unstudied" : 1
"unsubdued" : 1
"unsuitableness" : 1
"unsuited" : 1
"unsuspected" : 1
"untied" : 1
"untouched" : 1
"untried" : 1
"unusually" : 1
"unwarily" : 1
"unworthiness" : 1
"uppermost" : 1
"upright" : 1
"uproar" : 1
"upstairs" : 1
"urgency" : 1
"usage" : 1
"useless" : 1
"uselessly" : 1
"ushered" : 1
"utility" : 1
"utterance" : 1
"vacate" : 1
"vague" : 1
"valleys" : 1
"valueless" : 1
"vanish" : 1
"variations" : 1
"varied" : 1
"ve" : 1
"veal" : 1
"venturing" : 1
"verbal" : 1
"vestibule" : 1
"vex" : 1
"vicinity" : 1
"viewed" : 1
"vigor" : 1
"vigour" : 1
"vile" : 1
"villages" : 1
"villainy" : 1
"violins" : 1
"violoncello" : 1
"virtues" : 1
"virtuous" : 1
"virulence" : 1
"volunteer" : 1
"vouchsafe" : 1
"vouchsafed" : 1
"vowed" : 1
"vulgarity" : 1
"w" : 1
"wager" : 1
"waistcoats" : 1
"walker" : 1
"walnut" : 1
"wander" : 1
"warehouse" : 1
"warmed" : 1
"warmest" : 1
"warning" : 1
"warranted" : 1
"washing" : 1
"weakening" : 1
"weaknesses" : 1
"wearing" : 1
"weathered" : 1
"wedding" : 1
"weddings" : 1
"west" : 1
"westerly" : 1
"westminster" : 1
"westward" : 1
"wettest" : 1
"weymouth" : 1
"whereas" : 1
"whiled" : 1
"whims" : 1
"whip" : 1
"whispering" : 1
"whitakers" : 1
"whiter" : 1
"whomsoever" : 1
"wicket" : 1
"wide" : 1
"widely" : 1
"widen" : 1
"widower" : 1
"wildest" : 1
"winks" : 1
"wiping" : 1
"wiser" : 1
"wisher" : 1
"withdrawn" : 1
"witnesses" : 1
"witnessing" : 1
"witticisms" : 1
"wittiest" : 1
"witty" : 1
"wonderer" : 1
"wont" : 1
"wooded" : 1
"woody" : 1
"worded" : 1
"worked" : 1
"workmen" : 1
"worlds" : 1
"worry" : 1
"worship" : 1
"worsted" : 1
"worthiest" : 1
"worthy" : 1
"wounded" : 1
"wrapped" : 1
"wrapt" : 1
"wrought" : 1
"wrung" : 1
"yard" : 1
"ye" : 1
"yielded" : 1
"zealously" : 1
