library("gWidgets")
library("rPython")
library("stringr")
library("ggplot2")
library("plotrix")
python.exec("from nltk.book import *")
python.exec("import nltk")
python.exec("from nltk.corpus import wordnet as wordname")
source("plotting.R")
pos.words = scan('positive_words.txt', what='character', comment.char=';')
neg.words = scan('negative_words.txt', what='character', comment.char=';')
source("senti.txt")
windows<-gwindow("Main Page")
mainwindows<-ggroup(horizontal=FALSE,container=windows)
glabel("1  :  For Concordance                         ",container=mainwindows)
glabel("2  :  For File Concordance                ",container=mainwindows)
glabel("3  :  For Frequency Distribution   ",container=mainwindows)
glabel("4  :  For Lexical Richness                  ",container=mainwindows)
glabel("5  :  For Long Words                           ",container=mainwindows)
glabel("6  :  For Sets                                           ",container=mainwindows)
glabel("7  :  For Word Info                             ",container=mainwindows)
glabel("8  :  For Word Match                         ",container=mainwindows)
glabel("9  :  For Dictionary                             ",container=mainwindows)
glabel("10 :  For Sentiment                               ",container=mainwindows)
windowgroup4<-ggroup(horizontal=TRUE,container=mainwindows)
label2<-glabel("Enter your choice ",container=windowgroup4)
text3<-gedit(container=windowgroup4)
btn2<-gbutton("Lets begin",container=mainwindows,handler=function(h,...)
{
texname<-svalue(text3)
source("main_page.R")
main_page(texname)
})




