window<-gwindow("Word Match")
mainwindow<-ggroup(horizontal=FALSE,container=window)
windowgroup1<-ggroup(horizontal=TRUE,container=mainwindow)
label1<-glabel("Enter the prefix    ",container=windowgroup1)
text1<-gedit(container=windowgroup1)
windowgroup2<-ggroup(horizontal=TRUE,container=mainwindow)
label2<-glabel("Enter the postfix ",container=windowgroup2)
text2<-gedit(container=windowgroup2)
windowgroup3<-ggroup(horizontal=TRUE,container=mainwindow)
label1<-glabel("Enter a file                                                                 ",container=windowgroup3)
btn<-gbutton("Browse",container=windowgroup3,handler=function(h,...)
{
prefix<-svalue(text1)
postfix<-svalue(text2)
path<-gfile()
source("word_match.R")
matching(path,prefix,postfix)
})
windowgroup4<-ggroup(horizontal=TRUE,container=mainwindow)
label2<-glabel("Enter bookname : ",container=windowgroup4)
text3<-gedit(container=windowgroup4)
btn2<-gbutton("Get Word Count",container=mainwindow,handler=function(h,...)
{
texname<-svalue(text3)
prefix<-svalue(text1)
postfix<-svalue(text2)
source("word_match.R")
matching(texname,prefix,postfix)
})


